import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiChangePasswordRequest,
  ApiLoginRequest,
  ApiRefreshTokenRequest,
  ApiRegisterRequest,
  RenderResponseApiAuthResponse,
  RenderResponseApiUserResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 用户登录
 */
export const postAuthLogin = (
  apiLoginRequest: ApiLoginRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiAuthResponse>>,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiLoginRequest,
    },
    options,
  );
};
/**
 * @summary 退出登录
 */
export const postAuthLogout = (
  options?: SecondParameter<typeof customInstance<RenderResponseWithoutData>>,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/auth/logout`, method: "POST" },
    options,
  );
};
/**
 * @summary 获取当前登录用户
 */
export const getAuthMe = (
  options?: SecondParameter<typeof customInstance<RenderResponseApiUserResponse>>,
) => {
  return customInstance<RenderResponseApiUserResponse>({ url: `/auth/me`, method: "GET" }, options);
};
/**
 * @summary 修改密码
 */
export const putAuthPassword = (
  apiChangePasswordRequest: ApiChangePasswordRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseWithoutData>>,
) => {
  return customInstance<RenderResponseWithoutData>(
    {
      url: `/auth/password`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiChangePasswordRequest,
    },
    options,
  );
};
/**
 * @summary 刷新登录凭证
 */
export const postAuthRefresh = (
  apiRefreshTokenRequest: ApiRefreshTokenRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiAuthResponse>>,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/auth/refresh`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiRefreshTokenRequest,
    },
    options,
  );
};
/**
 * @summary 用户注册
 */
export const postAuthRegister = (
  apiRegisterRequest: ApiRegisterRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiAuthResponse>>,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiRegisterRequest,
    },
    options,
  );
};
export type PostAuthLoginResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>;
export type PostAuthLogoutResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>;
export type GetAuthMeResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>;
export type PutAuthPasswordResult = NonNullable<Awaited<ReturnType<typeof putAuthPassword>>>;
export type PostAuthRefreshResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>;
export type PostAuthRegisterResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>;
