/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  ApiChangePasswordRequest,
  ApiCreateAPIKeyRequest,
  ApiLoginRequest,
  ApiRefreshTokenRequest,
  ApiRegisterRequest,
  RenderErrorResponse,
  RenderResponseApiAuthResponse,
  RenderResponseApiCreateAPIKeyResponse,
  RenderResponseApiUserResponse,
  RenderResponseArrayApiApiKeyResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 获取 API Key 列表
 */
export const getAuthApiKeys = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiApiKeyResponse>(
    { url: `/auth/api-keys`, method: "GET", signal },
    options,
  );
};

export const getGetAuthApiKeysQueryKey = () => {
  return [`/auth/api-keys`] as const;
};

export const getGetAuthApiKeysQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthApiKeys>>,
  TError = RenderErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKeys>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthApiKeysQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthApiKeys>>> = ({ signal }) =>
    getAuthApiKeys(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthApiKeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthApiKeys>>>;
export type GetAuthApiKeysQueryError = RenderErrorResponse;

export function useGetAuthApiKeys<
  TData = Awaited<ReturnType<typeof getAuthApiKeys>>,
  TError = RenderErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKeys>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getAuthApiKeys>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthApiKeys<
  TData = Awaited<ReturnType<typeof getAuthApiKeys>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKeys>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthApiKeys>>,
          TError,
          Awaited<ReturnType<typeof getAuthApiKeys>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthApiKeys<
  TData = Awaited<ReturnType<typeof getAuthApiKeys>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取 API Key 列表
 */

export function useGetAuthApiKeys<
  TData = Awaited<ReturnType<typeof getAuthApiKeys>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthApiKeys>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthApiKeysQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 创建 API Key
 */
export const postAuthApiKeys = (
  apiCreateAPIKeyRequest: ApiCreateAPIKeyRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiCreateAPIKeyResponse>(
    {
      url: `/auth/api-keys`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateAPIKeyRequest,
      signal,
    },
    options,
  );
};

export const getPostAuthApiKeysMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthApiKeys>>,
    TError,
    { data: ApiCreateAPIKeyRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthApiKeys>>,
  TError,
  { data: ApiCreateAPIKeyRequest },
  TContext
> => {
  const mutationKey = ["postAuthApiKeys"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthApiKeys>>,
    { data: ApiCreateAPIKeyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthApiKeys(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthApiKeysMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthApiKeys>>
>;
export type PostAuthApiKeysMutationBody = ApiCreateAPIKeyRequest;
export type PostAuthApiKeysMutationError = RenderErrorResponse;

/**
 * @summary 创建 API Key
 */
export const usePostAuthApiKeys = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthApiKeys>>,
      TError,
      { data: ApiCreateAPIKeyRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthApiKeys>>,
  TError,
  { data: ApiCreateAPIKeyRequest },
  TContext
> => {
  return useMutation(getPostAuthApiKeysMutationOptions(options), queryClient);
};
/**
 * @summary 撤销 API Key
 */
export const deleteAuthApiKeysKeyId = (
  keyId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/auth/api-keys/${keyId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteAuthApiKeysKeyIdMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthApiKeysKeyId>>,
    TError,
    { keyId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthApiKeysKeyId>>,
  TError,
  { keyId: string },
  TContext
> => {
  const mutationKey = ["deleteAuthApiKeysKeyId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthApiKeysKeyId>>,
    { keyId: string }
  > = (props) => {
    const { keyId } = props ?? {};

    return deleteAuthApiKeysKeyId(keyId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthApiKeysKeyIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthApiKeysKeyId>>
>;

export type DeleteAuthApiKeysKeyIdMutationError = RenderErrorResponse;

/**
 * @summary 撤销 API Key
 */
export const useDeleteAuthApiKeysKeyId = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthApiKeysKeyId>>,
      TError,
      { keyId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAuthApiKeysKeyId>>,
  TError,
  { keyId: string },
  TContext
> => {
  return useMutation(getDeleteAuthApiKeysKeyIdMutationOptions(options), queryClient);
};
/**
 * @summary 用户登录
 */
export const postAuthLogin = (
  apiLoginRequest: ApiLoginRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiLoginRequest,
      signal,
    },
    options,
  );
};

export const getPostAuthLoginMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    { data: ApiLoginRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: ApiLoginRequest },
  TContext
> => {
  const mutationKey = ["postAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLogin>>,
    { data: ApiLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>;
export type PostAuthLoginMutationBody = ApiLoginRequest;
export type PostAuthLoginMutationError = RenderErrorResponse;

/**
 * @summary 用户登录
 */
export const usePostAuthLogin = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogin>>,
      TError,
      { data: ApiLoginRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLogin>>,
  TError,
  { data: ApiLoginRequest },
  TContext
> => {
  return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
};
/**
 * @summary 退出登录
 */
export const postAuthLogout = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/auth/logout`, method: "POST", signal },
    options,
  );
};

export const getPostAuthLogoutMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  const mutationKey = ["postAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
    return postAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>;

export type PostAuthLogoutMutationError = RenderErrorResponse;

/**
 * @summary 退出登录
 */
export const usePostAuthLogout = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
};
/**
 * @summary 获取当前登录用户
 */
export const getAuthMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiUserResponse>(
    { url: `/auth/me`, method: "GET", signal },
    options,
  );
};

export const getGetAuthMeQueryKey = () => {
  return [`/auth/me`] as const;
};

export const getGetAuthMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = RenderErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) =>
    getAuthMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>;
export type GetAuthMeQueryError = RenderErrorResponse;

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = RenderErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getAuthMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取当前登录用户
 */

export function useGetAuthMe<
  TData = Awaited<ReturnType<typeof getAuthMe>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 修改密码
 */
export const putAuthPassword = (
  apiChangePasswordRequest: ApiChangePasswordRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    {
      url: `/auth/password`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiChangePasswordRequest,
      signal,
    },
    options,
  );
};

export const getPutAuthPasswordMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAuthPassword>>,
    TError,
    { data: ApiChangePasswordRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAuthPassword>>,
  TError,
  { data: ApiChangePasswordRequest },
  TContext
> => {
  const mutationKey = ["putAuthPassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAuthPassword>>,
    { data: ApiChangePasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return putAuthPassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAuthPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAuthPassword>>
>;
export type PutAuthPasswordMutationBody = ApiChangePasswordRequest;
export type PutAuthPasswordMutationError = RenderErrorResponse;

/**
 * @summary 修改密码
 */
export const usePutAuthPassword = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAuthPassword>>,
      TError,
      { data: ApiChangePasswordRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putAuthPassword>>,
  TError,
  { data: ApiChangePasswordRequest },
  TContext
> => {
  return useMutation(getPutAuthPasswordMutationOptions(options), queryClient);
};
/**
 * @summary 刷新登录凭证
 */
export const postAuthRefresh = (
  apiRefreshTokenRequest: ApiRefreshTokenRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/auth/refresh`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiRefreshTokenRequest,
      signal,
    },
    options,
  );
};

export const getPostAuthRefreshMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    TError,
    { data: ApiRefreshTokenRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRefresh>>,
  TError,
  { data: ApiRefreshTokenRequest },
  TContext
> => {
  const mutationKey = ["postAuthRefresh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRefresh>>,
    { data: ApiRefreshTokenRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRefresh(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRefresh>>
>;
export type PostAuthRefreshMutationBody = ApiRefreshTokenRequest;
export type PostAuthRefreshMutationError = RenderErrorResponse;

/**
 * @summary 刷新登录凭证
 */
export const usePostAuthRefresh = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRefresh>>,
      TError,
      { data: ApiRefreshTokenRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRefresh>>,
  TError,
  { data: ApiRefreshTokenRequest },
  TContext
> => {
  return useMutation(getPostAuthRefreshMutationOptions(options), queryClient);
};
/**
 * @summary 用户注册
 */
export const postAuthRegister = (
  apiRegisterRequest: ApiRegisterRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiRegisterRequest,
      signal,
    },
    options,
  );
};

export const getPostAuthRegisterMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: ApiRegisterRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: ApiRegisterRequest },
  TContext
> => {
  const mutationKey = ["postAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRegister>>,
    { data: ApiRegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody = ApiRegisterRequest;
export type PostAuthRegisterMutationError = RenderErrorResponse;

/**
 * @summary 用户注册
 */
export const usePostAuthRegister = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRegister>>,
      TError,
      { data: ApiRegisterRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: ApiRegisterRequest },
  TContext
> => {
  return useMutation(getPostAuthRegisterMutationOptions(options), queryClient);
};
