import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  GetUsersUserIdFollowersParams,
  GetUsersUserIdFollowingParams,
  RenderResponseApiFollowStatusResponse,
  RenderResponseArrayApiFollowUserResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 取消关注
 */
export const deleteUsersUserIdFollow = (
  userId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiFollowStatusResponse>>,
) => {
  return customInstance<RenderResponseApiFollowStatusResponse>(
    { url: `/users/${userId}/follow`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 关注用户
 */
export const putUsersUserIdFollow = (
  userId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiFollowStatusResponse>>,
) => {
  return customInstance<RenderResponseApiFollowStatusResponse>(
    { url: `/users/${userId}/follow`, method: "PUT" },
    options,
  );
};
/**
 * @summary 获取粉丝列表
 */
export const getUsersUserIdFollowers = (
  userId: string,
  params?: GetUsersUserIdFollowersParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiFollowUserResponse>>,
) => {
  return customInstance<RenderResponseArrayApiFollowUserResponse>(
    { url: `/users/${userId}/followers`, method: "GET", params },
    options,
  );
};
/**
 * @summary 获取关注列表
 */
export const getUsersUserIdFollowing = (
  userId: string,
  params?: GetUsersUserIdFollowingParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiFollowUserResponse>>,
) => {
  return customInstance<RenderResponseArrayApiFollowUserResponse>(
    { url: `/users/${userId}/following`, method: "GET", params },
    options,
  );
};
export type DeleteUsersUserIdFollowResult = NonNullable<
  Awaited<ReturnType<typeof deleteUsersUserIdFollow>>
>;
export type PutUsersUserIdFollowResult = NonNullable<
  Awaited<ReturnType<typeof putUsersUserIdFollow>>
>;
export type GetUsersUserIdFollowersResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUserIdFollowers>>
>;
export type GetUsersUserIdFollowingResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUserIdFollowing>>
>;
