/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  GetUsersUserIdFollowersParams,
  GetUsersUserIdFollowingParams,
  RenderErrorResponse,
  RenderResponseApiFollowStatusResponse,
  RenderResponseApiPageResponseApiFollowUserResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 取消关注
 */
export const deleteUsersUserIdFollow = (
  userId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiFollowStatusResponse>(
    { url: `/users/${userId}/follow`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteUsersUserIdFollowMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUsersUserIdFollow>>,
    TError,
    { userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUsersUserIdFollow>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ["deleteUsersUserIdFollow"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteUsersUserIdFollow>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {};

    return deleteUsersUserIdFollow(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUsersUserIdFollowMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteUsersUserIdFollow>>
>;

export type DeleteUsersUserIdFollowMutationError = RenderErrorResponse;

/**
 * @summary 取消关注
 */
export const useDeleteUsersUserIdFollow = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUsersUserIdFollow>>,
      TError,
      { userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteUsersUserIdFollow>>,
  TError,
  { userId: string },
  TContext
> => {
  return useMutation(getDeleteUsersUserIdFollowMutationOptions(options), queryClient);
};
/**
 * @summary 关注用户
 */
export const putUsersUserIdFollow = (
  userId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiFollowStatusResponse>(
    { url: `/users/${userId}/follow`, method: "PUT", signal },
    options,
  );
};

export const getPutUsersUserIdFollowMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putUsersUserIdFollow>>,
    TError,
    { userId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putUsersUserIdFollow>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ["putUsersUserIdFollow"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putUsersUserIdFollow>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {};

    return putUsersUserIdFollow(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutUsersUserIdFollowMutationResult = NonNullable<
  Awaited<ReturnType<typeof putUsersUserIdFollow>>
>;

export type PutUsersUserIdFollowMutationError = RenderErrorResponse;

/**
 * @summary 关注用户
 */
export const usePutUsersUserIdFollow = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putUsersUserIdFollow>>,
      TError,
      { userId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putUsersUserIdFollow>>,
  TError,
  { userId: string },
  TContext
> => {
  return useMutation(getPutUsersUserIdFollowMutationOptions(options), queryClient);
};
/**
 * @summary 获取粉丝列表
 */
export const getUsersUserIdFollowers = (
  userId: string,
  params?: GetUsersUserIdFollowersParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiFollowUserResponse>(
    { url: `/users/${userId}/followers`, method: "GET", params, signal },
    options,
  );
};

export const getGetUsersUserIdFollowersQueryKey = (
  userId: string,
  params?: GetUsersUserIdFollowersParams,
) => {
  return [`/users/${userId}/followers`, ...(params ? [params] : [])] as const;
};

export const getGetUsersUserIdFollowersQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersUserIdFollowersQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersUserIdFollowers>>> = ({
    signal,
  }) => getUsersUserIdFollowers(userId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowers>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetUsersUserIdFollowersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUserIdFollowers>>
>;
export type GetUsersUserIdFollowersQueryError = RenderErrorResponse;

export function useGetUsersUserIdFollowers<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params: undefined | GetUsersUserIdFollowersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserIdFollowers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersUserIdFollowers<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserIdFollowers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersUserIdFollowers<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取粉丝列表
 */

export function useGetUsersUserIdFollowers<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowers>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowers>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUsersUserIdFollowersQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取关注列表
 */
export const getUsersUserIdFollowing = (
  userId: string,
  params?: GetUsersUserIdFollowingParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiFollowUserResponse>(
    { url: `/users/${userId}/following`, method: "GET", params, signal },
    options,
  );
};

export const getGetUsersUserIdFollowingQueryKey = (
  userId: string,
  params?: GetUsersUserIdFollowingParams,
) => {
  return [`/users/${userId}/following`, ...(params ? [params] : [])] as const;
};

export const getGetUsersUserIdFollowingQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowing>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersUserIdFollowingQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersUserIdFollowing>>> = ({
    signal,
  }) => getUsersUserIdFollowing(userId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowing>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetUsersUserIdFollowingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUserIdFollowing>>
>;
export type GetUsersUserIdFollowingQueryError = RenderErrorResponse;

export function useGetUsersUserIdFollowing<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params: undefined | GetUsersUserIdFollowingParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowing>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserIdFollowing>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersUserIdFollowing<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowing>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserIdFollowing>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersUserIdFollowing<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowing>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取关注列表
 */

export function useGetUsersUserIdFollowing<
  TData = Awaited<ReturnType<typeof getUsersUserIdFollowing>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdFollowing>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUsersUserIdFollowingQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
