/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  GetMeLikesParams,
  RenderErrorResponse,
  RenderResponseApiLikeStatusResponse,
  RenderResponseApiPageResponseApiListPostsItemResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 取消点赞评论
 */
export const deleteCommentsCommentIdLike = (
  commentId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/comments/${commentId}/like`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteCommentsCommentIdLikeMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>,
    TError,
    { commentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>,
  TError,
  { commentId: string },
  TContext
> => {
  const mutationKey = ["deleteCommentsCommentIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>,
    { commentId: string }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteCommentsCommentIdLike(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentsCommentIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>
>;

export type DeleteCommentsCommentIdLikeMutationError = RenderErrorResponse;

/**
 * @summary 取消点赞评论
 */
export const useDeleteCommentsCommentIdLike = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>,
      TError,
      { commentId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>,
  TError,
  { commentId: string },
  TContext
> => {
  return useMutation(getDeleteCommentsCommentIdLikeMutationOptions(options), queryClient);
};
/**
 * @summary 点赞评论
 */
export const putCommentsCommentIdLike = (
  commentId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/comments/${commentId}/like`, method: "PUT", signal },
    options,
  );
};

export const getPutCommentsCommentIdLikeMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putCommentsCommentIdLike>>,
    TError,
    { commentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putCommentsCommentIdLike>>,
  TError,
  { commentId: string },
  TContext
> => {
  const mutationKey = ["putCommentsCommentIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putCommentsCommentIdLike>>,
    { commentId: string }
  > = (props) => {
    const { commentId } = props ?? {};

    return putCommentsCommentIdLike(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutCommentsCommentIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putCommentsCommentIdLike>>
>;

export type PutCommentsCommentIdLikeMutationError = RenderErrorResponse;

/**
 * @summary 点赞评论
 */
export const usePutCommentsCommentIdLike = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putCommentsCommentIdLike>>,
      TError,
      { commentId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putCommentsCommentIdLike>>,
  TError,
  { commentId: string },
  TContext
> => {
  return useMutation(getPutCommentsCommentIdLikeMutationOptions(options), queryClient);
};
/**
 * @summary 获取我点赞的帖子
 */
export const getMeLikes = (
  params?: GetMeLikesParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiListPostsItemResponse>(
    { url: `/me/likes`, method: "GET", params, signal },
    options,
  );
};

export const getGetMeLikesQueryKey = (params?: GetMeLikesParams) => {
  return [`/me/likes`, ...(params ? [params] : [])] as const;
};

export const getGetMeLikesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeLikes>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeLikesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeLikes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeLikesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeLikes>>> = ({ signal }) =>
    getMeLikes(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeLikes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeLikesQueryResult = NonNullable<Awaited<ReturnType<typeof getMeLikes>>>;
export type GetMeLikesQueryError = RenderErrorResponse;

export function useGetMeLikes<
  TData = Awaited<ReturnType<typeof getMeLikes>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetMeLikesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeLikes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeLikes>>,
          TError,
          Awaited<ReturnType<typeof getMeLikes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeLikes<
  TData = Awaited<ReturnType<typeof getMeLikes>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeLikesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeLikes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeLikes>>,
          TError,
          Awaited<ReturnType<typeof getMeLikes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeLikes<
  TData = Awaited<ReturnType<typeof getMeLikes>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeLikesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeLikes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取我点赞的帖子
 */

export function useGetMeLikes<
  TData = Awaited<ReturnType<typeof getMeLikes>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeLikesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeLikes>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeLikesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 取消点赞帖子
 */
export const deletePostsPostIdLike = (
  postId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/posts/${postId}/like`, method: "DELETE", signal },
    options,
  );
};

export const getDeletePostsPostIdLikeMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostsPostIdLike>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostsPostIdLike>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ["deletePostsPostIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostsPostIdLike>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return deletePostsPostIdLike(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostsPostIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsPostIdLike>>
>;

export type DeletePostsPostIdLikeMutationError = RenderErrorResponse;

/**
 * @summary 取消点赞帖子
 */
export const useDeletePostsPostIdLike = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostsPostIdLike>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostsPostIdLike>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getDeletePostsPostIdLikeMutationOptions(options), queryClient);
};
/**
 * @summary 点赞帖子
 */
export const putPostsPostIdLike = (
  postId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/posts/${postId}/like`, method: "PUT", signal },
    options,
  );
};

export const getPutPostsPostIdLikeMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putPostsPostIdLike>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putPostsPostIdLike>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ["putPostsPostIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putPostsPostIdLike>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return putPostsPostIdLike(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutPostsPostIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putPostsPostIdLike>>
>;

export type PutPostsPostIdLikeMutationError = RenderErrorResponse;

/**
 * @summary 点赞帖子
 */
export const usePutPostsPostIdLike = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putPostsPostIdLike>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putPostsPostIdLike>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getPutPostsPostIdLikeMutationOptions(options), queryClient);
};
