import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type { ApiToggleLikeRequest, RenderResponseApiToggleLikeResponse } from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 切换点赞状态
 */
export const postLikes = (
  apiToggleLikeRequest: ApiToggleLikeRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiToggleLikeResponse>>,
) => {
  return customInstance<RenderResponseApiToggleLikeResponse>(
    {
      url: `/likes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiToggleLikeRequest,
    },
    options,
  );
};
export type PostLikesResult = NonNullable<Awaited<ReturnType<typeof postLikes>>>;
