import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type { RenderResponseApiLikeStatusResponse } from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 取消点赞评论
 */
export const deleteCommentsCommentIdLike = (
  commentId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiLikeStatusResponse>>,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/comments/${commentId}/like`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 点赞评论
 */
export const putCommentsCommentIdLike = (
  commentId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiLikeStatusResponse>>,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/comments/${commentId}/like`, method: "PUT" },
    options,
  );
};
/**
 * @summary 取消点赞帖子
 */
export const deletePostsPostIdLike = (
  postId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiLikeStatusResponse>>,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/posts/${postId}/like`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 点赞帖子
 */
export const putPostsPostIdLike = (
  postId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiLikeStatusResponse>>,
) => {
  return customInstance<RenderResponseApiLikeStatusResponse>(
    { url: `/posts/${postId}/like`, method: "PUT" },
    options,
  );
};
export type DeleteCommentsCommentIdLikeResult = NonNullable<
  Awaited<ReturnType<typeof deleteCommentsCommentIdLike>>
>;
export type PutCommentsCommentIdLikeResult = NonNullable<
  Awaited<ReturnType<typeof putCommentsCommentIdLike>>
>;
export type DeletePostsPostIdLikeResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsPostIdLike>>
>;
export type PutPostsPostIdLikeResult = NonNullable<Awaited<ReturnType<typeof putPostsPostIdLike>>>;
