import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type { ApiUpdateProfileRequest, RenderResponseApiUserResponse } from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取用户资料
 */
export const getUsersUserId = (
  userId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiUserResponse>>,
) => {
  return customInstance<RenderResponseApiUserResponse>(
    { url: `/users/${userId}`, method: "GET" },
    options,
  );
};
/**
 * @summary 更新用户资料
 */
export const putUsersProfile = (
  apiUpdateProfileRequest: ApiUpdateProfileRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiUserResponse>>,
) => {
  return customInstance<RenderResponseApiUserResponse>(
    {
      url: `/users/profile`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiUpdateProfileRequest,
    },
    options,
  );
};
export type GetUsersUserIdResult = NonNullable<Awaited<ReturnType<typeof getUsersUserId>>>;
export type PutUsersProfileResult = NonNullable<Awaited<ReturnType<typeof putUsersProfile>>>;
