import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiLoginRequest,
  ApiRegisterRequest,
  ApiUpdateProfileRequest,
  RenderResponseApiAuthResponse,
  RenderResponseApiUserResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取用户资料
 */
export const getUsersUserId = (
  userId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiUserResponse>>,
) => {
  return customInstance<RenderResponseApiUserResponse>(
    { url: `/users/${userId}`, method: "GET" },
    options,
  );
};
/**
 * @summary 用户登录
 */
export const postUsersLogin = (
  apiLoginRequest: ApiLoginRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiAuthResponse>>,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/users/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiLoginRequest,
    },
    options,
  );
};
/**
 * @summary 更新用户资料
 */
export const putUsersProfile = (
  apiUpdateProfileRequest: ApiUpdateProfileRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiUserResponse>>,
) => {
  return customInstance<RenderResponseApiUserResponse>(
    {
      url: `/users/profile`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiUpdateProfileRequest,
    },
    options,
  );
};
/**
 * @summary 用户注册
 */
export const postUsersRegister = (
  apiRegisterRequest: ApiRegisterRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiAuthResponse>>,
) => {
  return customInstance<RenderResponseApiAuthResponse>(
    {
      url: `/users/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiRegisterRequest,
    },
    options,
  );
};
export type GetUsersUserIdResult = NonNullable<Awaited<ReturnType<typeof getUsersUserId>>>;
export type PostUsersLoginResult = NonNullable<Awaited<ReturnType<typeof postUsersLogin>>>;
export type PutUsersProfileResult = NonNullable<Awaited<ReturnType<typeof putUsersProfile>>>;
export type PostUsersRegisterResult = NonNullable<Awaited<ReturnType<typeof postUsersRegister>>>;
