/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
/**
 * 用户信息
 */
export interface ApiUserResponse {
  /** 头像地址 */
  avatar_url?: string;
  /** 个人简介 */
  bio?: string;
  /** 用户 ID */
  id?: string;
  /** 用户名 */
  username?: string;
}

export interface ApiAuthResponse {
  /** JWT token */
  token?: string;
  user?: ApiUserResponse;
}

/**
 * 作者信息
 */
export interface ApiAuthorResponse {
  /** 头像地址 */
  avatar_url?: string;
  /** 用户 ID */
  id?: string;
  /** 用户名 */
  username?: string;
}

export interface ApiCommentResponse {
  /** 作者头像地址 */
  author_avatar?: string;
  /** 作者用户名 */
  author_username?: string;
  /** 评论内容 */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 评论 ID */
  id?: string;
  /** 点赞数 */
  like_count?: number;
  /** 父评论 ID,顶级评论为 nil */
  parent_id?: string;
  /** 帖子 ID */
  post_id?: string;
  /** 用户 ID */
  user_id?: string;
}

export interface ApiCreateCommentRequest {
  /**
   * 评论内容
   * @maxLength 1000
   */
  content: string;
  /** 父评论 ID,如果是顶级评论则为 nil */
  parent_id?: string;
  /** 帖子唯一标识 ID */
  post_id: string;
}

export interface ApiCreateCommentResponse {
  /** 评论 ID */
  id?: string;
}

/**
 * 媒体类型 (image/video)
 */
export type ApiCreateMediaItemMediaType =
  (typeof ApiCreateMediaItemMediaType)[keyof typeof ApiCreateMediaItemMediaType];

export const ApiCreateMediaItemMediaType = {
  image: "image",
  video: "video",
} as const;

export interface ApiCreateMediaItem {
  /** 媒体类型 (image/video) */
  media_type: ApiCreateMediaItemMediaType;
  /** 媒体 URL */
  media_url: string;
  /** 排序序号 */
  sort_order?: number;
}

export interface ApiCreatePostRequest {
  /** 帖子内容 */
  content: string;
  /** 媒体列表 */
  media?: ApiCreateMediaItem[];
  /**
   * 帖子标题
   * @maxLength 200
   */
  title: string;
}

export interface ApiCreatePostResponse {
  /** 帖子 ID */
  id?: string;
}

export interface ApiFollowResponse {
  /** 操作是否成功 */
  ok?: boolean;
}

export interface ApiFollowUserResponse {
  /** 头像地址 */
  avatar_url?: string;
  /** 个人简介 */
  bio?: string;
  /** 用户 ID */
  id?: string;
  /** 用户名 */
  username?: string;
}

export interface ApiMediaResponse {
  /** 媒体 ID */
  id?: string;
  /** 媒体类型 */
  media_type?: string;
  /** 媒体 URL */
  media_url?: string;
  /** 排序序号 */
  sort_order?: number;
}

export interface ApiGetPostsResponse {
  author?: ApiAuthorResponse;
  /** 内容 */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 帖子 ID */
  id?: string;
  /** 媒体列表 */
  media?: ApiMediaResponse[];
  /** 标题 */
  title?: string;
  /** 浏览量 */
  view_count?: number;
}

export interface ApiListPostsItemResponse {
  author?: ApiAuthorResponse;
  /** 内容 */
  content?: string;
  /** 封面 URL */
  cover_url?: string;
  /** 创建时间 */
  created_at?: string;
  /** 帖子 ID */
  id?: string;
  /** 标题 */
  title?: string;
  /** 浏览量 */
  view_count?: number;
}

export interface ApiLoginRequest {
  /** 密码 */
  password: string;
  /** 用户名 */
  username: string;
}

export interface ApiRegisterRequest {
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 32
   */
  username: string;
}

/**
 * 目标类型 (1=帖子, 2=评论)
 */
export type ApiToggleLikeRequestTargetType =
  (typeof ApiToggleLikeRequestTargetType)[keyof typeof ApiToggleLikeRequestTargetType];

export const ApiToggleLikeRequestTargetType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export interface ApiToggleLikeRequest {
  /** 目标 ID (帖子 ID 或 评论 ID) */
  target_id?: string;
  /** 目标类型 (1=帖子, 2=评论) */
  target_type: ApiToggleLikeRequestTargetType;
}

export interface ApiToggleLikeResponse {
  /** 是否点赞成功 */
  ok?: boolean;
}

export interface ApiUpdateProfileRequest {
  /** 头像 URL */
  avatar_url?: string;
  /**
   * 个人简介
   * @maxLength 200
   */
  bio?: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 32
   */
  username: string;
}

export interface RenderResponseApiAuthResponse {
  code?: number;
  data?: ApiAuthResponse;
  msg?: string;
}

export interface RenderResponseApiCreateCommentResponse {
  code?: number;
  data?: ApiCreateCommentResponse;
  msg?: string;
}

export interface RenderResponseApiCreatePostResponse {
  code?: number;
  data?: ApiCreatePostResponse;
  msg?: string;
}

export interface RenderResponseApiFollowResponse {
  code?: number;
  data?: ApiFollowResponse;
  msg?: string;
}

export interface RenderResponseApiGetPostsResponse {
  code?: number;
  data?: ApiGetPostsResponse;
  msg?: string;
}

export interface RenderResponseApiToggleLikeResponse {
  code?: number;
  data?: ApiToggleLikeResponse;
  msg?: string;
}

export interface RenderResponseApiUserResponse {
  code?: number;
  data?: ApiUserResponse;
  msg?: string;
}

export interface RenderResponseArrayApiCommentResponse {
  code?: number;
  data?: ApiCommentResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiFollowUserResponse {
  code?: number;
  data?: ApiFollowUserResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiListPostsItemResponse {
  code?: number;
  data?: ApiListPostsItemResponse[];
  msg?: string;
}

export interface RenderResponseWithoutData {
  code?: number;
  msg?: string;
}

export interface RenderErrorResponse {
  code?: number;
  msg?: string;
}

export type GetPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsPostIdCommentsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsUserUserIdParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdFollowersParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdFollowingParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};
