/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
/**
 * 用户信息
 */
export interface ApiUserResponse {
  /** 头像地址 */
  avatar_url: string;
  /** 个人简介 */
  bio: string;
  /** 用户 ID */
  id: string;
  /** 用户名 */
  username: string;
}

export interface ApiAuthResponse {
  /** Access token */
  access_token: string;
  /**
   * Access token 有效期,单位为秒
   * @minimum 0
   */
  expires_in: number;
  /** Refresh token */
  refresh_token: string;
  user: ApiUserResponse;
}

/**
 * 作者信息
 */
export interface ApiAuthorResponse {
  /** 头像地址 */
  avatar_url: string;
  /** 用户 ID */
  id: string;
  /** 用户名 */
  username: string;
  /** 当前用户是否已关注作者 */
  viewer_following: boolean;
}

export interface ApiChangePasswordRequest {
  /**
   * 新密码
   * @minLength 6
   * @maxLength 128
   */
  new_password: string;
  /** 当前密码 */
  old_password: string;
}

export interface ApiCollectPostRequest {
  /** 收藏夹 ID,可选 */
  folder_id?: string;
}

export interface ApiCollectionStatusResponse {
  /**
   * 收藏数量
   * @minimum 0
   */
  collect_count: number;
  /** 是否已收藏 */
  viewer_collected: boolean;
}

export interface ApiCommentResponse {
  /** 作者头像地址 */
  author_avatar: string;
  /** 作者用户名 */
  author_username: string;
  /** 评论内容 */
  content: string;
  /** 创建时间 */
  created_at: string;
  /** 评论 ID */
  id: string;
  /**
   * 点赞数
   * @minimum 0
   */
  like_count: number;
  /** 父评论 ID,顶级评论为 nil */
  parent_id?: string;
  /** 帖子 ID */
  post_id: string;
  /** 用户 ID */
  user_id: string;
  /** 当前用户是否已点赞 */
  viewer_liked: boolean;
}

export interface ApiCreateCommentRequest {
  /**
   * 评论内容
   * @maxLength 1000
   */
  content: string;
  /** 父评论 ID,如果是顶级评论则为 nil */
  parent_id?: string;
  /** 帖子唯一标识 ID */
  post_id: string;
}

export interface ApiCreateFolderRequest {
  /**
   * 收藏夹名称
   * @maxLength 50
   */
  name: string;
}

/**
 * 媒体类型 (image/video)
 */
export type ApiCreateMediaItemMediaType =
  (typeof ApiCreateMediaItemMediaType)[keyof typeof ApiCreateMediaItemMediaType];

export const ApiCreateMediaItemMediaType = {
  image: "image",
  video: "video",
} as const;

export interface ApiCreateMediaItem {
  /** 媒体对象 key */
  media_key: string;
  /** 媒体类型 (image/video) */
  media_type: ApiCreateMediaItemMediaType;
  /** 排序序号 */
  sort_order?: number;
}

export interface ApiCreatePostRequest {
  /** 帖子内容 */
  content: string;
  /** 媒体列表 */
  media?: ApiCreateMediaItem[];
  /** 标签名称 */
  tags?: string[];
  /**
   * 帖子标题
   * @maxLength 100
   */
  title: string;
}

export interface ApiCreatePostResponse {
  /** 帖子 ID */
  id: string;
}

export interface ApiCreateTagRequest {
  /**
   * 标签描述
   * @maxLength 200
   */
  description?: string;
  /**
   * 标签名称
   * @maxLength 50
   */
  name: string;
}

export interface ApiDeleteCommentResponse {
  /** @minimum 0 */
  comment_count: number;
  id: string;
  post_id: string;
}

export interface ApiFolderResponse {
  /** 创建时间 */
  created_at: string;
  /** 收藏夹 ID */
  id: string;
  /** 收藏夹名称 */
  name: string;
}

export interface ApiFollowStatusResponse {
  /**
   * 该用户粉丝数
   * @minimum 0
   */
  follower_count: number;
  /** 是否已关注 */
  viewer_following: boolean;
}

export interface ApiFollowUserResponse {
  /** 头像地址 */
  avatar_url: string;
  /** 个人简介 */
  bio: string;
  /** 用户 ID */
  id: string;
  /** 用户名 */
  username: string;
  /** 当前用户是否已关注 */
  viewer_following: boolean;
}

export interface ApiMediaResponse {
  /**
   * 图片高度
   * @minimum 0
   */
  height: number;
  /** 媒体 ID */
  id: string;
  /** 媒体类型 */
  media_type: string;
  /** 媒体 CDN URL */
  media_url: string;
  /**
   * 排序序号
   * @minimum 0
   */
  sort_order: number;
  /**
   * 图片宽度
   * @minimum 0
   */
  width: number;
}

export interface ApiTagResponse {
  /** 创建时间 */
  created_at: string;
  /** 标签描述 */
  description: string;
  /** 标签 ID */
  id: string;
  /** 标签名称 */
  name: string;
  /**
   * 帖子数量
   * @minimum 0
   */
  post_count: number;
}

export interface ApiGetPostsResponse {
  author: ApiAuthorResponse;
  /**
   * 收藏数
   * @minimum 0
   */
  collect_count: number;
  /**
   * 评论数
   * @minimum 0
   */
  comment_count: number;
  /** 内容 */
  content: string;
  /** 创建时间 */
  created_at: string;
  /** 帖子 ID */
  id: string;
  /**
   * 点赞数
   * @minimum 0
   */
  like_count: number;
  /** 媒体列表 */
  media: ApiMediaResponse[];
  /** 标签列表 */
  tags: ApiTagResponse[];
  /** 标题 */
  title: string;
  /**
   * 浏览量
   * @minimum 0
   */
  view_count: number;
  /** 当前用户是否已收藏 */
  viewer_collected: boolean;
  /** 当前用户是否已点赞 */
  viewer_liked: boolean;
}

export interface ApiLikeStatusResponse {
  /**
   * 点赞数量
   * @minimum 0
   */
  like_count: number;
  /** 是否已点赞 */
  viewer_liked: boolean;
}

export interface ApiListPostsItemResponse {
  author: ApiAuthorResponse;
  /**
   * 收藏数
   * @minimum 0
   */
  collect_count: number;
  /**
   * 评论数
   * @minimum 0
   */
  comment_count: number;
  /** 内容 */
  content: string;
  /** 封面 URL */
  cover_url: string;
  /** 创建时间 */
  created_at: string;
  /** 帖子 ID */
  id: string;
  /**
   * 点赞数
   * @minimum 0
   */
  like_count: number;
  /** 标题 */
  title: string;
  /**
   * 浏览量
   * @minimum 0
   */
  view_count: number;
  /** 当前用户是否已收藏 */
  viewer_collected: boolean;
  /** 当前用户是否已点赞 */
  viewer_liked: boolean;
}

export interface ApiLoginRequest {
  /** 密码 */
  password: string;
  /** 用户名 */
  username: string;
}

export interface ApiPageResponseApiCommentResponse {
  items: ApiCommentResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiPageResponseApiFolderResponse {
  items: ApiFolderResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiPageResponseApiFollowUserResponse {
  items: ApiFollowUserResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiPageResponseApiListPostsItemResponse {
  items: ApiListPostsItemResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiSearchHistoryResponse {
  keyword: string;
  searched_at: string;
}

export interface ApiPageResponseApiSearchHistoryResponse {
  items: ApiSearchHistoryResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiPageResponseApiTagResponse {
  items: ApiTagResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiTopicResponse {
  /** 封面地址 */
  cover_url: string;
  /** 创建时间 */
  created_at: string;
  /** 专题描述 */
  description: string;
  /** 专题 ID */
  id: string;
  /** 专题名称 */
  name: string;
  /**
   * 专题帖子数量
   * @minimum 0
   */
  post_count: number;
}

export interface ApiPageResponseApiTopicResponse {
  items: ApiTopicResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiTrendingSearchResponse {
  keyword: string;
  /** @minimum 0 */
  search_count: number;
}

export interface ApiPageResponseApiTrendingSearchResponse {
  items: ApiTrendingSearchResponse[];
  /** @minimum 1 */
  page: number;
  /** @minimum 1 */
  page_size: number;
  /** @minimum 0 */
  total: number;
}

export interface ApiPresignMediaRequest {
  /** 文件 MIME 类型 */
  content_type: string;
}

export interface ApiPresignMediaResponse {
  /**
   * 上传地址有效期,单位为秒
   * @minimum 0
   */
  expires_in: number;
  /** 对象存储 key,发布帖子时作为媒体 URL 使用 */
  object_key: string;
  /** 上传地址 */
  upload_url: string;
}

export interface ApiRefreshTokenRequest {
  refresh_token: string;
}

export interface ApiRegisterRequest {
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 32
   */
  username: string;
}

export interface ApiSearchResponse {
  posts: ApiPageResponseApiListPostsItemResponse;
  tags: ApiPageResponseApiTagResponse;
  users: ApiPageResponseApiFollowUserResponse;
}

export interface ApiUpdateFolderRequest {
  /**
   * 收藏夹名称
   * @maxLength 50
   */
  name: string;
}

export interface ApiUpdatePostRequest {
  /** 帖子内容 */
  content: string;
  /** 媒体列表 */
  media?: ApiCreateMediaItem[];
  /** 标签名称 */
  tags?: string[];
  /**
   * 帖子标题
   * @maxLength 100
   */
  title: string;
}

export interface ApiUpdateProfileRequest {
  /** 头像 URL */
  avatar_url?: string;
  /**
   * 个人简介
   * @maxLength 200
   */
  bio?: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 32
   */
  username: string;
}

export interface ApiUserProfileResponse {
  avatar_url: string;
  bio: string;
  /** @minimum 0 */
  follower_count: number;
  /** @minimum 0 */
  following_count: number;
  id: string;
  /** @minimum 0 */
  post_count: number;
  /** @minimum 0 */
  received_like_and_collect_count: number;
  username: string;
  viewer_following: boolean;
}

export interface RenderResponseApiAuthResponse {
  code?: number;
  data?: ApiAuthResponse;
  msg?: string;
}

export interface RenderResponseApiCollectionStatusResponse {
  code?: number;
  data?: ApiCollectionStatusResponse;
  msg?: string;
}

export interface RenderResponseApiCommentResponse {
  code?: number;
  data?: ApiCommentResponse;
  msg?: string;
}

export interface RenderResponseApiCreatePostResponse {
  code?: number;
  data?: ApiCreatePostResponse;
  msg?: string;
}

export interface RenderResponseApiDeleteCommentResponse {
  code?: number;
  data?: ApiDeleteCommentResponse;
  msg?: string;
}

export interface RenderResponseApiFolderResponse {
  code?: number;
  data?: ApiFolderResponse;
  msg?: string;
}

export interface RenderResponseApiFollowStatusResponse {
  code?: number;
  data?: ApiFollowStatusResponse;
  msg?: string;
}

export interface RenderResponseApiGetPostsResponse {
  code?: number;
  data?: ApiGetPostsResponse;
  msg?: string;
}

export interface RenderResponseApiLikeStatusResponse {
  code?: number;
  data?: ApiLikeStatusResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiCommentResponse {
  code?: number;
  data?: ApiPageResponseApiCommentResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiFolderResponse {
  code?: number;
  data?: ApiPageResponseApiFolderResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiFollowUserResponse {
  code?: number;
  data?: ApiPageResponseApiFollowUserResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiListPostsItemResponse {
  code?: number;
  data?: ApiPageResponseApiListPostsItemResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiSearchHistoryResponse {
  code?: number;
  data?: ApiPageResponseApiSearchHistoryResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiTopicResponse {
  code?: number;
  data?: ApiPageResponseApiTopicResponse;
  msg?: string;
}

export interface RenderResponseApiPageResponseApiTrendingSearchResponse {
  code?: number;
  data?: ApiPageResponseApiTrendingSearchResponse;
  msg?: string;
}

export interface RenderResponseApiPresignMediaResponse {
  code?: number;
  data?: ApiPresignMediaResponse;
  msg?: string;
}

export interface RenderResponseApiSearchResponse {
  code?: number;
  data?: ApiSearchResponse;
  msg?: string;
}

export interface RenderResponseApiTagResponse {
  code?: number;
  data?: ApiTagResponse;
  msg?: string;
}

export interface RenderResponseApiTopicResponse {
  code?: number;
  data?: ApiTopicResponse;
  msg?: string;
}

export interface RenderResponseApiUserProfileResponse {
  code?: number;
  data?: ApiUserProfileResponse;
  msg?: string;
}

export interface RenderResponseApiUserResponse {
  code?: number;
  data?: ApiUserResponse;
  msg?: string;
}

export interface RenderResponseWithoutData {
  code?: number;
  msg?: string;
}

export interface RenderErrorResponse {
  code?: number;
  msg?: string;
}

export type GetFeedRecommendedParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetMeCollectionsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetMeCollectionsFoldersParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetMeSearchHistoryParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsPostIdCommentsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetSearchParams = {
  /**
   * 搜索关键词
   */
  q: string;
  /**
   * 搜索类型: all/posts/users/tags
   */
  type?: string;
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetSearchSuggestionsParams = {
  /**
   * 关键词
   */
  q: string;
};

export type GetSearchTrendingParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetTagsTagIdPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetTopicsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetTopicsTopicIdPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdFollowersParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdFollowingParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};
