/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
/**
 * 用户信息
 */
export interface ApiUserResponse {
  /** 头像地址 */
  avatar_url?: string;
  /** 个人简介 */
  bio?: string;
  /** 用户 ID */
  id?: string;
  /** 用户名 */
  username?: string;
}

export interface ApiAuthResponse {
  /** Access token */
  access_token?: string;
  /** Access token 有效期,单位为秒 */
  expires_in?: number;
  /** Refresh token */
  refresh_token?: string;
  user?: ApiUserResponse;
}

/**
 * 作者信息
 */
export interface ApiAuthorResponse {
  /** 头像地址 */
  avatar_url?: string;
  /** 用户 ID */
  id?: string;
  /** 用户名 */
  username?: string;
}

export interface ApiChangePasswordRequest {
  /**
   * 新密码
   * @minLength 6
   * @maxLength 128
   */
  new_password: string;
  /** 当前密码 */
  old_password: string;
}

export interface ApiCollectPostRequest {
  /** 收藏夹 ID,可选 */
  folder_id?: string;
}

export interface ApiCollectionItemResponse {
  author?: ApiAuthorResponse;
  /** 收藏数 */
  collect_count?: number;
  /** 收藏时间 */
  collected_at?: string;
  /** 评论数 */
  comment_count?: number;
  /** 内容 */
  content?: string;
  /** 封面 URL */
  cover_url?: string;
  /** 帖子 ID */
  id?: string;
  /** 点赞数 */
  like_count?: number;
  /** 标题 */
  title?: string;
  /** 浏览量 */
  view_count?: number;
}

export interface ApiCollectionStatusResponse {
  /** 收藏数量 */
  collect_count?: number;
  /** 是否已收藏 */
  collected?: boolean;
}

export interface ApiCommentResponse {
  /** 作者头像地址 */
  author_avatar?: string;
  /** 作者用户名 */
  author_username?: string;
  /** 评论内容 */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 评论 ID */
  id?: string;
  /** 点赞数 */
  like_count?: number;
  /** 父评论 ID,顶级评论为 nil */
  parent_id?: string;
  /** 帖子 ID */
  post_id?: string;
  /** 用户 ID */
  user_id?: string;
}

export interface ApiCreateCommentRequest {
  /**
   * 评论内容
   * @maxLength 1000
   */
  content: string;
  /** 父评论 ID,如果是顶级评论则为 nil */
  parent_id?: string;
  /** 帖子唯一标识 ID */
  post_id: string;
}

export interface ApiCreateCommentResponse {
  /** 评论 ID */
  id?: string;
}

export interface ApiCreateFolderRequest {
  /**
   * 收藏夹名称
   * @maxLength 50
   */
  name: string;
}

/**
 * 媒体类型 (image/video)
 */
export type ApiCreateMediaItemMediaType =
  (typeof ApiCreateMediaItemMediaType)[keyof typeof ApiCreateMediaItemMediaType];

export const ApiCreateMediaItemMediaType = {
  image: "image",
  video: "video",
} as const;

export interface ApiCreateMediaItem {
  /** 媒体类型 (image/video) */
  media_type: ApiCreateMediaItemMediaType;
  /** 媒体 URL */
  media_url: string;
  /** 排序序号 */
  sort_order?: number;
}

export interface ApiCreatePostRequest {
  /** 帖子内容 */
  content: string;
  /** 媒体列表 */
  media?: ApiCreateMediaItem[];
  /** 标签名称 */
  tags?: string[];
  /**
   * 帖子标题
   * @maxLength 100
   */
  title: string;
}

export interface ApiCreatePostResponse {
  /** 帖子 ID */
  id?: string;
}

export interface ApiCreateTagRequest {
  /**
   * 标签描述
   * @maxLength 200
   */
  description?: string;
  /**
   * 标签名称
   * @maxLength 50
   */
  name: string;
}

export interface ApiFolderResponse {
  /** 创建时间 */
  created_at?: string;
  /** 收藏夹 ID */
  id?: string;
  /** 收藏夹名称 */
  name?: string;
}

export interface ApiFollowStatusResponse {
  /** 该用户粉丝数 */
  follower_count?: number;
  /** 是否已关注 */
  following?: boolean;
}

export interface ApiFollowUserResponse {
  /** 头像地址 */
  avatar_url?: string;
  /** 个人简介 */
  bio?: string;
  /** 用户 ID */
  id?: string;
  /** 用户名 */
  username?: string;
}

export interface ApiMediaResponse {
  /** 媒体 ID */
  id?: string;
  /** 媒体类型 */
  media_type?: string;
  /** 媒体 URL */
  media_url?: string;
  /** 排序序号 */
  sort_order?: number;
}

export interface ApiTagResponse {
  /** 创建时间 */
  created_at?: string;
  /** 标签描述 */
  description?: string;
  /** 标签 ID */
  id?: string;
  /** 标签名称 */
  name?: string;
  /** 帖子数量 */
  post_count?: number;
}

export interface ApiGetPostsResponse {
  author?: ApiAuthorResponse;
  /** 收藏数 */
  collect_count?: number;
  /** 当前用户是否已收藏 */
  collected?: boolean;
  /** 评论数 */
  comment_count?: number;
  /** 内容 */
  content?: string;
  /** 创建时间 */
  created_at?: string;
  /** 帖子 ID */
  id?: string;
  /** 点赞数 */
  like_count?: number;
  /** 当前用户是否已点赞 */
  liked?: boolean;
  /** 媒体列表 */
  media?: ApiMediaResponse[];
  /** 标签列表 */
  tags?: ApiTagResponse[];
  /** 标题 */
  title?: string;
  /** 浏览量 */
  view_count?: number;
}

export interface ApiLikeStatusResponse {
  /** 点赞数量 */
  like_count?: number;
  /** 是否已点赞 */
  liked?: boolean;
}

export interface ApiListPostsItemResponse {
  author?: ApiAuthorResponse;
  /** 收藏数 */
  collect_count?: number;
  /** 评论数 */
  comment_count?: number;
  /** 内容 */
  content?: string;
  /** 封面 URL */
  cover_url?: string;
  /** 创建时间 */
  created_at?: string;
  /** 帖子 ID */
  id?: string;
  /** 点赞数 */
  like_count?: number;
  /** 标题 */
  title?: string;
  /** 浏览量 */
  view_count?: number;
}

export interface ApiLoginRequest {
  /** 密码 */
  password: string;
  /** 用户名 */
  username: string;
}

export interface ApiPresignMediaRequest {
  /** 文件 MIME 类型 */
  content_type: string;
}

export interface ApiPresignMediaResponse {
  /** 上传地址有效期,单位为秒 */
  expires_in?: number;
  /** 对象存储 key,发布帖子时作为媒体 URL 使用 */
  object_key?: string;
  /** 上传地址 */
  upload_url?: string;
}

export interface ApiRefreshTokenRequest {
  refresh_token: string;
}

export interface ApiRegisterRequest {
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 32
   */
  username: string;
}

export interface ApiSearchHistoryResponse {
  keyword?: string;
  searched_at?: string;
}

export interface ApiSearchPostResponse {
  author?: ApiAuthorResponse;
  collect_count?: number;
  comment_count?: number;
  content?: string;
  cover_url?: string;
  created_at?: string;
  id?: string;
  like_count?: number;
  relevance?: number;
  title?: string;
  view_count?: number;
}

export interface ApiSearchResponse {
  posts?: ApiSearchPostResponse[];
  tags?: ApiTagResponse[];
  users?: ApiFollowUserResponse[];
}

export interface ApiTopicResponse {
  /** 封面地址 */
  cover_url?: string;
  /** 创建时间 */
  created_at?: string;
  /** 专题描述 */
  description?: string;
  /** 专题 ID */
  id?: string;
  /** 专题名称 */
  name?: string;
  /** 专题帖子数量 */
  post_count?: number;
}

export interface ApiTrendingSearchResponse {
  keyword?: string;
  search_count?: number;
}

export interface ApiUpdateFolderRequest {
  /**
   * 收藏夹名称
   * @maxLength 50
   */
  name: string;
}

export interface ApiUpdatePostRequest {
  /** 帖子内容 */
  content: string;
  /** 媒体列表 */
  media?: ApiCreateMediaItem[];
  /** 标签名称 */
  tags?: string[];
  /**
   * 帖子标题
   * @maxLength 100
   */
  title: string;
}

export interface ApiUpdateProfileRequest {
  /** 头像 URL */
  avatar_url?: string;
  /**
   * 个人简介
   * @maxLength 200
   */
  bio?: string;
  /**
   * 用户名
   * @minLength 3
   * @maxLength 32
   */
  username: string;
}

export interface RenderResponseApiAuthResponse {
  code?: number;
  data?: ApiAuthResponse;
  msg?: string;
}

export interface RenderResponseApiCollectionStatusResponse {
  code?: number;
  data?: ApiCollectionStatusResponse;
  msg?: string;
}

export interface RenderResponseApiCreateCommentResponse {
  code?: number;
  data?: ApiCreateCommentResponse;
  msg?: string;
}

export interface RenderResponseApiCreatePostResponse {
  code?: number;
  data?: ApiCreatePostResponse;
  msg?: string;
}

export interface RenderResponseApiFolderResponse {
  code?: number;
  data?: ApiFolderResponse;
  msg?: string;
}

export interface RenderResponseApiFollowStatusResponse {
  code?: number;
  data?: ApiFollowStatusResponse;
  msg?: string;
}

export interface RenderResponseApiGetPostsResponse {
  code?: number;
  data?: ApiGetPostsResponse;
  msg?: string;
}

export interface RenderResponseApiLikeStatusResponse {
  code?: number;
  data?: ApiLikeStatusResponse;
  msg?: string;
}

export interface RenderResponseApiPresignMediaResponse {
  code?: number;
  data?: ApiPresignMediaResponse;
  msg?: string;
}

export interface RenderResponseApiSearchResponse {
  code?: number;
  data?: ApiSearchResponse;
  msg?: string;
}

export interface RenderResponseApiTagResponse {
  code?: number;
  data?: ApiTagResponse;
  msg?: string;
}

export interface RenderResponseApiTopicResponse {
  code?: number;
  data?: ApiTopicResponse;
  msg?: string;
}

export interface RenderResponseApiUserResponse {
  code?: number;
  data?: ApiUserResponse;
  msg?: string;
}

export interface RenderResponseArrayApiCollectionItemResponse {
  code?: number;
  data?: ApiCollectionItemResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiCommentResponse {
  code?: number;
  data?: ApiCommentResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiFolderResponse {
  code?: number;
  data?: ApiFolderResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiFollowUserResponse {
  code?: number;
  data?: ApiFollowUserResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiListPostsItemResponse {
  code?: number;
  data?: ApiListPostsItemResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiSearchHistoryResponse {
  code?: number;
  data?: ApiSearchHistoryResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiTopicResponse {
  code?: number;
  data?: ApiTopicResponse[];
  msg?: string;
}

export interface RenderResponseArrayApiTrendingSearchResponse {
  code?: number;
  data?: ApiTrendingSearchResponse[];
  msg?: string;
}

export interface RenderResponseWithoutData {
  code?: number;
  msg?: string;
}

export interface RenderErrorResponse {
  code?: number;
  msg?: string;
}

export type GetFeedRecommendedParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetMeCollectionsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsPostIdCommentsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetPostsUserUserIdParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetSearchParams = {
  /**
   * 搜索关键词
   */
  q: string;
  /**
   * 搜索类型: all/posts/users/tags
   */
  type?: string;
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetSearchSuggestionsParams = {
  /**
   * 关键词
   */
  q: string;
};

export type GetSearchTrendingParams = {
  /**
   * 数量
   */
  limit?: number;
};

export type GetTagsTagIdPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetTopicsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetTopicsTopicIdPostsParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdFollowersParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};

export type GetUsersUserIdFollowingParams = {
  /**
   * 页码
   */
  page?: number;
  /**
   * 每页数量
   */
  page_size?: number;
};
