/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  GetNotificationsParams,
  RenderErrorResponse,
  RenderResponseApiPageResponseApiNotificationResponse,
  RenderResponseApiUnreadNotificationCountResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 获取通知列表
 */
export const getNotifications = (
  params?: GetNotificationsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiNotificationResponse>(
    { url: `/notifications`, method: "GET", params, signal },
    options,
  );
};

export const getGetNotificationsQueryKey = (params?: GetNotificationsParams) => {
  return [`/notifications`, ...(params ? [params] : [])] as const;
};

export const getGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = RenderErrorResponse,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNotificationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotifications>>> = ({ signal }) =>
    getNotifications(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotifications>>>;
export type GetNotificationsQueryError = RenderErrorResponse;

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetNotificationsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = RenderErrorResponse,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = RenderErrorResponse,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取通知列表
 */

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = RenderErrorResponse,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNotificationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 标记通知为已读
 */
export const patchNotificationsNotificationIdRead = (
  notificationId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/notifications/${notificationId}/read`, method: "PATCH", signal },
    options,
  );
};

export const getPatchNotificationsNotificationIdReadMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchNotificationsNotificationIdRead>>,
    TError,
    { notificationId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchNotificationsNotificationIdRead>>,
  TError,
  { notificationId: string },
  TContext
> => {
  const mutationKey = ["patchNotificationsNotificationIdRead"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchNotificationsNotificationIdRead>>,
    { notificationId: string }
  > = (props) => {
    const { notificationId } = props ?? {};

    return patchNotificationsNotificationIdRead(notificationId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchNotificationsNotificationIdReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchNotificationsNotificationIdRead>>
>;

export type PatchNotificationsNotificationIdReadMutationError = RenderErrorResponse;

/**
 * @summary 标记通知为已读
 */
export const usePatchNotificationsNotificationIdRead = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchNotificationsNotificationIdRead>>,
      TError,
      { notificationId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchNotificationsNotificationIdRead>>,
  TError,
  { notificationId: string },
  TContext
> => {
  return useMutation(getPatchNotificationsNotificationIdReadMutationOptions(options), queryClient);
};
/**
 * @summary 标记全部通知为已读
 */
export const postNotificationsReadAll = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/notifications/read-all`, method: "POST", signal },
    options,
  );
};

export const getPostNotificationsReadAllMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postNotificationsReadAll>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postNotificationsReadAll>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postNotificationsReadAll"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postNotificationsReadAll>>,
    void
  > = () => {
    return postNotificationsReadAll(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostNotificationsReadAllMutationResult = NonNullable<
  Awaited<ReturnType<typeof postNotificationsReadAll>>
>;

export type PostNotificationsReadAllMutationError = RenderErrorResponse;

/**
 * @summary 标记全部通知为已读
 */
export const usePostNotificationsReadAll = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postNotificationsReadAll>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postNotificationsReadAll>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getPostNotificationsReadAllMutationOptions(options), queryClient);
};
/**
 * @summary 获取未读通知数量
 */
export const getNotificationsUnreadCount = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiUnreadNotificationCountResponse>(
    { url: `/notifications/unread-count`, method: "GET", signal },
    options,
  );
};

export const getGetNotificationsUnreadCountQueryKey = () => {
  return [`/notifications/unread-count`] as const;
};

export const getGetNotificationsUnreadCountQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
  TError = RenderErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getNotificationsUnreadCount>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNotificationsUnreadCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotificationsUnreadCount>>> = ({
    signal,
  }) => getNotificationsUnreadCount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsUnreadCountQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNotificationsUnreadCount>>
>;
export type GetNotificationsUnreadCountQueryError = RenderErrorResponse;

export function useGetNotificationsUnreadCount<
  TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
  TError = RenderErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationsUnreadCount>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof getNotificationsUnreadCount>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotificationsUnreadCount<
  TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationsUnreadCount>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
          TError,
          Awaited<ReturnType<typeof getNotificationsUnreadCount>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotificationsUnreadCount<
  TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationsUnreadCount>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取未读通知数量
 */

export function useGetNotificationsUnreadCount<
  TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNotificationsUnreadCount>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNotificationsUnreadCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
