import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type { ApiPresignMediaRequest, RenderResponseApiPresignMediaResponse } from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取媒体上传地址
 */
export const postMediaPresign = (
  apiPresignMediaRequest: ApiPresignMediaRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiPresignMediaResponse>>,
) => {
  return customInstance<RenderResponseApiPresignMediaResponse>(
    {
      url: `/media/presign`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiPresignMediaRequest,
    },
    options,
  );
};
export type PostMediaPresignResult = NonNullable<Awaited<ReturnType<typeof postMediaPresign>>>;
