/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  ApiPresignMediaRequest,
  RenderErrorResponse,
  RenderResponseApiPresignMediaResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取媒体上传地址
 */
export const postMediaPresign = (
  apiPresignMediaRequest: ApiPresignMediaRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPresignMediaResponse>(
    {
      url: `/media/presign`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiPresignMediaRequest,
      signal,
    },
    options,
  );
};

export const getPostMediaPresignMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMediaPresign>>,
    TError,
    { data: ApiPresignMediaRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMediaPresign>>,
  TError,
  { data: ApiPresignMediaRequest },
  TContext
> => {
  const mutationKey = ["postMediaPresign"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMediaPresign>>,
    { data: ApiPresignMediaRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postMediaPresign(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMediaPresignMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMediaPresign>>
>;
export type PostMediaPresignMutationBody = ApiPresignMediaRequest;
export type PostMediaPresignMutationError = RenderErrorResponse;

/**
 * @summary 获取媒体上传地址
 */
export const usePostMediaPresign = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMediaPresign>>,
      TError,
      { data: ApiPresignMediaRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMediaPresign>>,
  TError,
  { data: ApiPresignMediaRequest },
  TContext
> => {
  return useMutation(getPostMediaPresignMutationOptions(options), queryClient);
};
