import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiCreateCommentRequest,
  GetPostsPostIdCommentsParams,
  RenderResponseApiCreateCommentResponse,
  RenderResponseArrayApiCommentResponse,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 创建评论
 */
export const postComments = (
  apiCreateCommentRequest: ApiCreateCommentRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiCreateCommentResponse>>,
) => {
  return customInstance<RenderResponseApiCreateCommentResponse>(
    {
      url: `/comments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateCommentRequest,
    },
    options,
  );
};
/**
 * @summary 获取帖子评论列表
 */
export const getPostsPostIdComments = (
  postId: string,
  params?: GetPostsPostIdCommentsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiCommentResponse>>,
) => {
  return customInstance<RenderResponseArrayApiCommentResponse>(
    { url: `/posts/${postId}/comments`, method: "GET", params },
    options,
  );
};
export type PostCommentsResult = NonNullable<Awaited<ReturnType<typeof postComments>>>;
export type GetPostsPostIdCommentsResult = NonNullable<
  Awaited<ReturnType<typeof getPostsPostIdComments>>
>;
