/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  ApiCreateCommentRequest,
  GetPostsPostIdCommentsParams,
  RenderErrorResponse,
  RenderResponseApiCreateCommentResponse,
  RenderResponseArrayApiCommentResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 创建评论
 */
export const postComments = (
  apiCreateCommentRequest: ApiCreateCommentRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiCreateCommentResponse>(
    {
      url: `/comments`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateCommentRequest,
      signal,
    },
    options,
  );
};

export const getPostCommentsMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postComments>>,
    TError,
    { data: ApiCreateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postComments>>,
  TError,
  { data: ApiCreateCommentRequest },
  TContext
> => {
  const mutationKey = ["postComments"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postComments>>,
    { data: ApiCreateCommentRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postComments(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCommentsMutationResult = NonNullable<Awaited<ReturnType<typeof postComments>>>;
export type PostCommentsMutationBody = ApiCreateCommentRequest;
export type PostCommentsMutationError = RenderErrorResponse;

/**
 * @summary 创建评论
 */
export const usePostComments = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postComments>>,
      TError,
      { data: ApiCreateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postComments>>,
  TError,
  { data: ApiCreateCommentRequest },
  TContext
> => {
  return useMutation(getPostCommentsMutationOptions(options), queryClient);
};
/**
 * @summary 删除评论
 */
export const deleteCommentsCommentId = (
  commentId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/comments/${commentId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteCommentsCommentIdMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCommentsCommentId>>,
    TError,
    { commentId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCommentsCommentId>>,
  TError,
  { commentId: string },
  TContext
> => {
  const mutationKey = ["deleteCommentsCommentId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCommentsCommentId>>,
    { commentId: string }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteCommentsCommentId(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentsCommentIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCommentsCommentId>>
>;

export type DeleteCommentsCommentIdMutationError = RenderErrorResponse;

/**
 * @summary 删除评论
 */
export const useDeleteCommentsCommentId = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCommentsCommentId>>,
      TError,
      { commentId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCommentsCommentId>>,
  TError,
  { commentId: string },
  TContext
> => {
  return useMutation(getDeleteCommentsCommentIdMutationOptions(options), queryClient);
};
/**
 * @summary 获取帖子评论列表
 */
export const getPostsPostIdComments = (
  postId: string,
  params?: GetPostsPostIdCommentsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiCommentResponse>(
    { url: `/posts/${postId}/comments`, method: "GET", params, signal },
    options,
  );
};

export const getGetPostsPostIdCommentsQueryKey = (
  postId: string,
  params?: GetPostsPostIdCommentsParams,
) => {
  return [`/posts/${postId}/comments`, ...(params ? [params] : [])] as const;
};

export const getGetPostsPostIdCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsPostIdComments>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  params?: GetPostsPostIdCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsPostIdCommentsQueryKey(postId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsPostIdComments>>> = ({ signal }) =>
    getPostsPostIdComments(postId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: postId !== null && postId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdComments>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPostsPostIdCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostsPostIdComments>>
>;
export type GetPostsPostIdCommentsQueryError = RenderErrorResponse;

export function useGetPostsPostIdComments<
  TData = Awaited<ReturnType<typeof getPostsPostIdComments>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  params: undefined | GetPostsPostIdCommentsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdComments>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostIdComments>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostIdComments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsPostIdComments<
  TData = Awaited<ReturnType<typeof getPostsPostIdComments>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  params?: GetPostsPostIdCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdComments>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostIdComments>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostIdComments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsPostIdComments<
  TData = Awaited<ReturnType<typeof getPostsPostIdComments>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  params?: GetPostsPostIdCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取帖子评论列表
 */

export function useGetPostsPostIdComments<
  TData = Awaited<ReturnType<typeof getPostsPostIdComments>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  params?: GetPostsPostIdCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostsPostIdComments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsPostIdCommentsQueryOptions(postId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
