/**
 * Generated by orval 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  ApiCollectPostRequest,
  ApiCreateFolderRequest,
  ApiUpdateFolderRequest,
  GetMeCollectionsFoldersFolderIdPostsParams,
  GetMeCollectionsFoldersParams,
  GetMeCollectionsParams,
  RenderErrorResponse,
  RenderResponseApiCollectionStatusResponse,
  RenderResponseApiFolderResponse,
  RenderResponseApiPageResponseApiFolderResponse,
  RenderResponseApiPageResponseApiListPostsItemResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 获取我的收藏列表
 */
export const getMeCollections = (
  params?: GetMeCollectionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiListPostsItemResponse>(
    { url: `/me/collections`, method: "GET", params, signal },
    options,
  );
};

export const getGetMeCollectionsQueryKey = (params?: GetMeCollectionsParams) => {
  return [`/me/collections`, ...(params ? [params] : [])] as const;
};

export const getGetMeCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeCollections>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeCollections>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeCollectionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeCollections>>> = ({ signal }) =>
    getMeCollections(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeCollectionsQueryResult = NonNullable<Awaited<ReturnType<typeof getMeCollections>>>;
export type GetMeCollectionsQueryError = RenderErrorResponse;

export function useGetMeCollections<
  TData = Awaited<ReturnType<typeof getMeCollections>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetMeCollectionsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeCollections>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeCollections>>,
          TError,
          Awaited<ReturnType<typeof getMeCollections>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeCollections<
  TData = Awaited<ReturnType<typeof getMeCollections>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeCollections>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeCollections>>,
          TError,
          Awaited<ReturnType<typeof getMeCollections>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeCollections<
  TData = Awaited<ReturnType<typeof getMeCollections>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeCollections>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取我的收藏列表
 */

export function useGetMeCollections<
  TData = Awaited<ReturnType<typeof getMeCollections>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeCollections>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeCollectionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取收藏夹列表
 */
export const getMeCollectionsFolders = (
  params?: GetMeCollectionsFoldersParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiFolderResponse>(
    { url: `/me/collections/folders`, method: "GET", params, signal },
    options,
  );
};

export const getGetMeCollectionsFoldersQueryKey = (params?: GetMeCollectionsFoldersParams) => {
  return [`/me/collections/folders`, ...(params ? [params] : [])] as const;
};

export const getGetMeCollectionsFoldersQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeCollectionsFolders>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeCollectionsFolders>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeCollectionsFoldersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeCollectionsFolders>>> = ({
    signal,
  }) => getMeCollectionsFolders(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeCollectionsFolders>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeCollectionsFoldersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMeCollectionsFolders>>
>;
export type GetMeCollectionsFoldersQueryError = RenderErrorResponse;

export function useGetMeCollectionsFolders<
  TData = Awaited<ReturnType<typeof getMeCollectionsFolders>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetMeCollectionsFoldersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeCollectionsFolders>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeCollectionsFolders>>,
          TError,
          Awaited<ReturnType<typeof getMeCollectionsFolders>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeCollectionsFolders<
  TData = Awaited<ReturnType<typeof getMeCollectionsFolders>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeCollectionsFolders>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeCollectionsFolders>>,
          TError,
          Awaited<ReturnType<typeof getMeCollectionsFolders>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeCollectionsFolders<
  TData = Awaited<ReturnType<typeof getMeCollectionsFolders>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeCollectionsFolders>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取收藏夹列表
 */

export function useGetMeCollectionsFolders<
  TData = Awaited<ReturnType<typeof getMeCollectionsFolders>>,
  TError = RenderErrorResponse,
>(
  params?: GetMeCollectionsFoldersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeCollectionsFolders>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeCollectionsFoldersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 创建收藏夹
 */
export const postMeCollectionsFolders = (
  apiCreateFolderRequest: ApiCreateFolderRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiFolderResponse>(
    {
      url: `/me/collections/folders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateFolderRequest,
      signal,
    },
    options,
  );
};

export const getPostMeCollectionsFoldersMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postMeCollectionsFolders>>,
    TError,
    { data: ApiCreateFolderRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postMeCollectionsFolders>>,
  TError,
  { data: ApiCreateFolderRequest },
  TContext
> => {
  const mutationKey = ["postMeCollectionsFolders"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postMeCollectionsFolders>>,
    { data: ApiCreateFolderRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postMeCollectionsFolders(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostMeCollectionsFoldersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postMeCollectionsFolders>>
>;
export type PostMeCollectionsFoldersMutationBody = ApiCreateFolderRequest;
export type PostMeCollectionsFoldersMutationError = RenderErrorResponse;

/**
 * @summary 创建收藏夹
 */
export const usePostMeCollectionsFolders = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postMeCollectionsFolders>>,
      TError,
      { data: ApiCreateFolderRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postMeCollectionsFolders>>,
  TError,
  { data: ApiCreateFolderRequest },
  TContext
> => {
  return useMutation(getPostMeCollectionsFoldersMutationOptions(options), queryClient);
};
/**
 * @summary 删除收藏夹
 */
export const deleteMeCollectionsFoldersFolderId = (
  folderId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/me/collections/folders/${folderId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteMeCollectionsFoldersFolderIdMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>,
    TError,
    { folderId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>,
  TError,
  { folderId: string },
  TContext
> => {
  const mutationKey = ["deleteMeCollectionsFoldersFolderId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>,
    { folderId: string }
  > = (props) => {
    const { folderId } = props ?? {};

    return deleteMeCollectionsFoldersFolderId(folderId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMeCollectionsFoldersFolderIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>
>;

export type DeleteMeCollectionsFoldersFolderIdMutationError = RenderErrorResponse;

/**
 * @summary 删除收藏夹
 */
export const useDeleteMeCollectionsFoldersFolderId = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>,
      TError,
      { folderId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>,
  TError,
  { folderId: string },
  TContext
> => {
  return useMutation(getDeleteMeCollectionsFoldersFolderIdMutationOptions(options), queryClient);
};
/**
 * @summary 修改收藏夹
 */
export const patchMeCollectionsFoldersFolderId = (
  folderId: string,
  apiUpdateFolderRequest: ApiUpdateFolderRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiFolderResponse>(
    {
      url: `/me/collections/folders/${folderId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: apiUpdateFolderRequest,
      signal,
    },
    options,
  );
};

export const getPatchMeCollectionsFoldersFolderIdMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>,
    TError,
    { folderId: string; data: ApiUpdateFolderRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>,
  TError,
  { folderId: string; data: ApiUpdateFolderRequest },
  TContext
> => {
  const mutationKey = ["patchMeCollectionsFoldersFolderId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>,
    { folderId: string; data: ApiUpdateFolderRequest }
  > = (props) => {
    const { folderId, data } = props ?? {};

    return patchMeCollectionsFoldersFolderId(folderId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchMeCollectionsFoldersFolderIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>
>;
export type PatchMeCollectionsFoldersFolderIdMutationBody = ApiUpdateFolderRequest;
export type PatchMeCollectionsFoldersFolderIdMutationError = RenderErrorResponse;

/**
 * @summary 修改收藏夹
 */
export const usePatchMeCollectionsFoldersFolderId = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>,
      TError,
      { folderId: string; data: ApiUpdateFolderRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>,
  TError,
  { folderId: string; data: ApiUpdateFolderRequest },
  TContext
> => {
  return useMutation(getPatchMeCollectionsFoldersFolderIdMutationOptions(options), queryClient);
};
/**
 * @summary 获取收藏夹中的帖子
 */
export const getMeCollectionsFoldersFolderIdPosts = (
  folderId: string,
  params?: GetMeCollectionsFoldersFolderIdPostsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiListPostsItemResponse>(
    { url: `/me/collections/folders/${folderId}/posts`, method: "GET", params, signal },
    options,
  );
};

export const getGetMeCollectionsFoldersFolderIdPostsQueryKey = (
  folderId: string,
  params?: GetMeCollectionsFoldersFolderIdPostsParams,
) => {
  return [`/me/collections/folders/${folderId}/posts`, ...(params ? [params] : [])] as const;
};

export const getGetMeCollectionsFoldersFolderIdPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
  TError = RenderErrorResponse,
>(
  folderId: string,
  params?: GetMeCollectionsFoldersFolderIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMeCollectionsFoldersFolderIdPostsQueryKey(folderId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>
  > = ({ signal }) =>
    getMeCollectionsFoldersFolderIdPosts(folderId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: folderId !== null && folderId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeCollectionsFoldersFolderIdPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>
>;
export type GetMeCollectionsFoldersFolderIdPostsQueryError = RenderErrorResponse;

export function useGetMeCollectionsFoldersFolderIdPosts<
  TData = Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
  TError = RenderErrorResponse,
>(
  folderId: string,
  params: undefined | GetMeCollectionsFoldersFolderIdPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeCollectionsFoldersFolderIdPosts<
  TData = Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
  TError = RenderErrorResponse,
>(
  folderId: string,
  params?: GetMeCollectionsFoldersFolderIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeCollectionsFoldersFolderIdPosts<
  TData = Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
  TError = RenderErrorResponse,
>(
  folderId: string,
  params?: GetMeCollectionsFoldersFolderIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取收藏夹中的帖子
 */

export function useGetMeCollectionsFoldersFolderIdPosts<
  TData = Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
  TError = RenderErrorResponse,
>(
  folderId: string,
  params?: GetMeCollectionsFoldersFolderIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMeCollectionsFoldersFolderIdPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeCollectionsFoldersFolderIdPostsQueryOptions(
    folderId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 取消收藏帖子
 */
export const deletePostsPostIdCollection = (
  postId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiCollectionStatusResponse>(
    { url: `/posts/${postId}/collection`, method: "DELETE", signal },
    options,
  );
};

export const getDeletePostsPostIdCollectionMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostsPostIdCollection>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostsPostIdCollection>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ["deletePostsPostIdCollection"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostsPostIdCollection>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return deletePostsPostIdCollection(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostsPostIdCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsPostIdCollection>>
>;

export type DeletePostsPostIdCollectionMutationError = RenderErrorResponse;

/**
 * @summary 取消收藏帖子
 */
export const useDeletePostsPostIdCollection = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostsPostIdCollection>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostsPostIdCollection>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getDeletePostsPostIdCollectionMutationOptions(options), queryClient);
};
/**
 * @summary 收藏帖子
 */
export const putPostsPostIdCollection = (
  postId: string,
  apiCollectPostRequest?: ApiCollectPostRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiCollectionStatusResponse>(
    {
      url: `/posts/${postId}/collection`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiCollectPostRequest,
      signal,
    },
    options,
  );
};

export const getPutPostsPostIdCollectionMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putPostsPostIdCollection>>,
    TError,
    { postId: string; data?: ApiCollectPostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putPostsPostIdCollection>>,
  TError,
  { postId: string; data?: ApiCollectPostRequest },
  TContext
> => {
  const mutationKey = ["putPostsPostIdCollection"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putPostsPostIdCollection>>,
    { postId: string; data?: ApiCollectPostRequest }
  > = (props) => {
    const { postId, data } = props ?? {};

    return putPostsPostIdCollection(postId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutPostsPostIdCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof putPostsPostIdCollection>>
>;
export type PutPostsPostIdCollectionMutationBody = ApiCollectPostRequest | undefined;
export type PutPostsPostIdCollectionMutationError = RenderErrorResponse;

/**
 * @summary 收藏帖子
 */
export const usePutPostsPostIdCollection = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putPostsPostIdCollection>>,
      TError,
      { postId: string; data?: ApiCollectPostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putPostsPostIdCollection>>,
  TError,
  { postId: string; data?: ApiCollectPostRequest },
  TContext
> => {
  return useMutation(getPutPostsPostIdCollectionMutationOptions(options), queryClient);
};
