import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiCollectPostRequest,
  ApiCreateFolderRequest,
  ApiUpdateFolderRequest,
  GetMeCollectionsParams,
  RenderResponseApiCollectionStatusResponse,
  RenderResponseApiFolderResponse,
  RenderResponseArrayApiCollectionItemResponse,
  RenderResponseArrayApiFolderResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取我的收藏列表
 */
export const getMeCollections = (
  params?: GetMeCollectionsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiCollectionItemResponse>>,
) => {
  return customInstance<RenderResponseArrayApiCollectionItemResponse>(
    { url: `/me/collections`, method: "GET", params },
    options,
  );
};
/**
 * @summary 获取收藏夹列表
 */
export const getMeCollectionsFolders = (
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiFolderResponse>>,
) => {
  return customInstance<RenderResponseArrayApiFolderResponse>(
    { url: `/me/collections/folders`, method: "GET" },
    options,
  );
};
/**
 * @summary 创建收藏夹
 */
export const postMeCollectionsFolders = (
  apiCreateFolderRequest: ApiCreateFolderRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiFolderResponse>>,
) => {
  return customInstance<RenderResponseApiFolderResponse>(
    {
      url: `/me/collections/folders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateFolderRequest,
    },
    options,
  );
};
/**
 * @summary 删除收藏夹
 */
export const deleteMeCollectionsFoldersFolderId = (
  folderId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseWithoutData>>,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/me/collections/folders/${folderId}`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 修改收藏夹
 */
export const patchMeCollectionsFoldersFolderId = (
  folderId: string,
  apiUpdateFolderRequest: ApiUpdateFolderRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiFolderResponse>>,
) => {
  return customInstance<RenderResponseApiFolderResponse>(
    {
      url: `/me/collections/folders/${folderId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: apiUpdateFolderRequest,
    },
    options,
  );
};
/**
 * @summary 取消收藏帖子
 */
export const deletePostsPostIdCollection = (
  postId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiCollectionStatusResponse>>,
) => {
  return customInstance<RenderResponseApiCollectionStatusResponse>(
    { url: `/posts/${postId}/collection`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 收藏帖子
 */
export const putPostsPostIdCollection = (
  postId: string,
  apiCollectPostRequest?: ApiCollectPostRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiCollectionStatusResponse>>,
) => {
  return customInstance<RenderResponseApiCollectionStatusResponse>(
    {
      url: `/posts/${postId}/collection`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: apiCollectPostRequest,
    },
    options,
  );
};
export type GetMeCollectionsResult = NonNullable<Awaited<ReturnType<typeof getMeCollections>>>;
export type GetMeCollectionsFoldersResult = NonNullable<
  Awaited<ReturnType<typeof getMeCollectionsFolders>>
>;
export type PostMeCollectionsFoldersResult = NonNullable<
  Awaited<ReturnType<typeof postMeCollectionsFolders>>
>;
export type DeleteMeCollectionsFoldersFolderIdResult = NonNullable<
  Awaited<ReturnType<typeof deleteMeCollectionsFoldersFolderId>>
>;
export type PatchMeCollectionsFoldersFolderIdResult = NonNullable<
  Awaited<ReturnType<typeof patchMeCollectionsFoldersFolderId>>
>;
export type DeletePostsPostIdCollectionResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsPostIdCollection>>
>;
export type PutPostsPostIdCollectionResult = NonNullable<
  Awaited<ReturnType<typeof putPostsPostIdCollection>>
>;
