import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiCreatePostRequest,
  ApiUpdatePostRequest,
  GetPostsParams,
  GetPostsUserUserIdParams,
  RenderResponseApiCreatePostResponse,
  RenderResponseApiGetPostsResponse,
  RenderResponseArrayApiListPostsItemResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取帖子列表
 */
export const getPosts = (
  params?: GetPostsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiListPostsItemResponse>>,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/posts`, method: "GET", params },
    options,
  );
};
/**
 * @summary 创建帖子
 */
export const postPosts = (
  apiCreatePostRequest: ApiCreatePostRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiCreatePostResponse>>,
) => {
  return customInstance<RenderResponseApiCreatePostResponse>(
    {
      url: `/posts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreatePostRequest,
    },
    options,
  );
};
/**
 * @summary 删除帖子
 */
export const deletePostsPostId = (
  postId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseWithoutData>>,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/posts/${postId}`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 获取帖子详情
 */
export const getPostsPostId = (
  postId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiGetPostsResponse>>,
) => {
  return customInstance<RenderResponseApiGetPostsResponse>(
    { url: `/posts/${postId}`, method: "GET" },
    options,
  );
};
/**
 * @summary 编辑帖子
 */
export const patchPostsPostId = (
  postId: string,
  apiUpdatePostRequest: ApiUpdatePostRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiCreatePostResponse>>,
) => {
  return customInstance<RenderResponseApiCreatePostResponse>(
    {
      url: `/posts/${postId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: apiUpdatePostRequest,
    },
    options,
  );
};
/**
 * @summary 获取指定用户的帖子列表
 */
export const getPostsUserUserId = (
  userId: string,
  params?: GetPostsUserUserIdParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiListPostsItemResponse>>,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/posts/user/${userId}`, method: "GET", params },
    options,
  );
};
export type GetPostsResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>;
export type PostPostsResult = NonNullable<Awaited<ReturnType<typeof postPosts>>>;
export type DeletePostsPostIdResult = NonNullable<Awaited<ReturnType<typeof deletePostsPostId>>>;
export type GetPostsPostIdResult = NonNullable<Awaited<ReturnType<typeof getPostsPostId>>>;
export type PatchPostsPostIdResult = NonNullable<Awaited<ReturnType<typeof patchPostsPostId>>>;
export type GetPostsUserUserIdResult = NonNullable<Awaited<ReturnType<typeof getPostsUserUserId>>>;
