/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  ApiCreatePostRequest,
  ApiUpdatePostRequest,
  GetPostsParams,
  GetUsersUserIdPostsParams,
  RenderErrorResponse,
  RenderResponseApiCreatePostResponse,
  RenderResponseApiGetPostsResponse,
  RenderResponseApiPageResponseApiListPostsItemResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 获取帖子列表
 */
export const getPosts = (
  params?: GetPostsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiListPostsItemResponse>(
    { url: `/posts`, method: "GET", params, signal },
    options,
  );
};

export const getGetPostsQueryKey = (params?: GetPostsParams) => {
  return [`/posts`, ...(params ? [params] : [])] as const;
};

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = RenderErrorResponse,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({ signal }) =>
    getPosts(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getPosts>>>;
export type GetPostsQueryError = RenderErrorResponse;

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetPostsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = RenderErrorResponse,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = RenderErrorResponse,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取帖子列表
 */

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = RenderErrorResponse,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 创建帖子
 */
export const postPosts = (
  apiCreatePostRequest: ApiCreatePostRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiCreatePostResponse>(
    {
      url: `/posts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreatePostRequest,
      signal,
    },
    options,
  );
};

export const getPostPostsMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPosts>>,
    TError,
    { data: ApiCreatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: ApiCreatePostRequest },
  TContext
> => {
  const mutationKey = ["postPosts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPosts>>,
    { data: ApiCreatePostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postPosts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsMutationResult = NonNullable<Awaited<ReturnType<typeof postPosts>>>;
export type PostPostsMutationBody = ApiCreatePostRequest;
export type PostPostsMutationError = RenderErrorResponse;

/**
 * @summary 创建帖子
 */
export const usePostPosts = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPosts>>,
      TError,
      { data: ApiCreatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: ApiCreatePostRequest },
  TContext
> => {
  return useMutation(getPostPostsMutationOptions(options), queryClient);
};
/**
 * @summary 删除帖子
 */
export const deletePostsPostId = (
  postId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/posts/${postId}`, method: "DELETE", signal },
    options,
  );
};

export const getDeletePostsPostIdMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostsPostId>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostsPostId>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ["deletePostsPostId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostsPostId>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return deletePostsPostId(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostsPostIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsPostId>>
>;

export type DeletePostsPostIdMutationError = RenderErrorResponse;

/**
 * @summary 删除帖子
 */
export const useDeletePostsPostId = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostsPostId>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostsPostId>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getDeletePostsPostIdMutationOptions(options), queryClient);
};
/**
 * @summary 获取帖子详情
 */
export const getPostsPostId = (
  postId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiGetPostsResponse>(
    { url: `/posts/${postId}`, method: "GET", signal },
    options,
  );
};

export const getGetPostsPostIdQueryKey = (postId: string) => {
  return [`/posts/${postId}`] as const;
};

export const getGetPostsPostIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsPostId>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsPostIdQueryKey(postId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsPostId>>> = ({ signal }) =>
    getPostsPostId(postId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: postId !== null && postId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetPostsPostIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPostsPostId>>>;
export type GetPostsPostIdQueryError = RenderErrorResponse;

export function useGetPostsPostId<
  TData = Awaited<ReturnType<typeof getPostsPostId>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsPostId<
  TData = Awaited<ReturnType<typeof getPostsPostId>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsPostId>>,
          TError,
          Awaited<ReturnType<typeof getPostsPostId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPostsPostId<
  TData = Awaited<ReturnType<typeof getPostsPostId>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取帖子详情
 */

export function useGetPostsPostId<
  TData = Awaited<ReturnType<typeof getPostsPostId>>,
  TError = RenderErrorResponse,
>(
  postId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPostsPostId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPostsPostIdQueryOptions(postId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 编辑帖子
 */
export const patchPostsPostId = (
  postId: string,
  apiUpdatePostRequest: ApiUpdatePostRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiCreatePostResponse>(
    {
      url: `/posts/${postId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: apiUpdatePostRequest,
      signal,
    },
    options,
  );
};

export const getPatchPostsPostIdMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchPostsPostId>>,
    TError,
    { postId: string; data: ApiUpdatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchPostsPostId>>,
  TError,
  { postId: string; data: ApiUpdatePostRequest },
  TContext
> => {
  const mutationKey = ["patchPostsPostId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchPostsPostId>>,
    { postId: string; data: ApiUpdatePostRequest }
  > = (props) => {
    const { postId, data } = props ?? {};

    return patchPostsPostId(postId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchPostsPostIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchPostsPostId>>
>;
export type PatchPostsPostIdMutationBody = ApiUpdatePostRequest;
export type PatchPostsPostIdMutationError = RenderErrorResponse;

/**
 * @summary 编辑帖子
 */
export const usePatchPostsPostId = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchPostsPostId>>,
      TError,
      { postId: string; data: ApiUpdatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchPostsPostId>>,
  TError,
  { postId: string; data: ApiUpdatePostRequest },
  TContext
> => {
  return useMutation(getPatchPostsPostIdMutationOptions(options), queryClient);
};
/**
 * @summary 获取指定用户的帖子列表
 */
export const getUsersUserIdPosts = (
  userId: string,
  params?: GetUsersUserIdPostsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiPageResponseApiListPostsItemResponse>(
    { url: `/users/${userId}/posts`, method: "GET", params, signal },
    options,
  );
};

export const getGetUsersUserIdPostsQueryKey = (
  userId: string,
  params?: GetUsersUserIdPostsParams,
) => {
  return [`/users/${userId}/posts`, ...(params ? [params] : [])] as const;
};

export const getGetUsersUserIdPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUsersUserIdPosts>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUsersUserIdPostsQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersUserIdPosts>>> = ({ signal }) =>
    getUsersUserIdPosts(userId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdPosts>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetUsersUserIdPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUsersUserIdPosts>>
>;
export type GetUsersUserIdPostsQueryError = RenderErrorResponse;

export function useGetUsersUserIdPosts<
  TData = Awaited<ReturnType<typeof getUsersUserIdPosts>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params: undefined | GetUsersUserIdPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersUserIdPosts<
  TData = Awaited<ReturnType<typeof getUsersUserIdPosts>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersUserIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getUsersUserIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUsersUserIdPosts<
  TData = Awaited<ReturnType<typeof getUsersUserIdPosts>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取指定用户的帖子列表
 */

export function useGetUsersUserIdPosts<
  TData = Awaited<ReturnType<typeof getUsersUserIdPosts>>,
  TError = RenderErrorResponse,
>(
  userId: string,
  params?: GetUsersUserIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUsersUserIdPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUsersUserIdPostsQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
