import { customInstance } from "../../mutator";
/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import type {
  ApiCreateTagRequest,
  GetFeedRecommendedParams,
  GetSearchParams,
  GetSearchSuggestionsParams,
  GetSearchTrendingParams,
  GetTagsTagIdPostsParams,
  GetTopicsParams,
  GetTopicsTopicIdPostsParams,
  RenderResponseApiSearchResponse,
  RenderResponseApiTagResponse,
  RenderResponseApiTopicResponse,
  RenderResponseArrayApiListPostsItemResponse,
  RenderResponseArrayApiSearchHistoryResponse,
  RenderResponseArrayApiTopicResponse,
  RenderResponseArrayApiTrendingSearchResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 获取发现流
 */
export const getFeedRecommended = (
  params?: GetFeedRecommendedParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiListPostsItemResponse>>,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/feed/recommended`, method: "GET", params },
    options,
  );
};
/**
 * @summary 清空搜索历史
 */
export const deleteMeSearchHistory = (
  options?: SecondParameter<typeof customInstance<RenderResponseWithoutData>>,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/me/search-history`, method: "DELETE" },
    options,
  );
};
/**
 * @summary 获取搜索历史
 */
export const getMeSearchHistory = (
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiSearchHistoryResponse>>,
) => {
  return customInstance<RenderResponseArrayApiSearchHistoryResponse>(
    { url: `/me/search-history`, method: "GET" },
    options,
  );
};
/**
 * @summary 综合搜索
 */
export const getSearch = (
  params: GetSearchParams,
  options?: SecondParameter<typeof customInstance<RenderResponseApiSearchResponse>>,
) => {
  return customInstance<RenderResponseApiSearchResponse>(
    { url: `/search`, method: "GET", params },
    options,
  );
};
/**
 * @summary 搜索联想
 */
export const getSearchSuggestions = (
  params: GetSearchSuggestionsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseApiSearchResponse>>,
) => {
  return customInstance<RenderResponseApiSearchResponse>(
    { url: `/search/suggestions`, method: "GET", params },
    options,
  );
};
/**
 * @summary 获取热搜词
 */
export const getSearchTrending = (
  params?: GetSearchTrendingParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiTrendingSearchResponse>>,
) => {
  return customInstance<RenderResponseArrayApiTrendingSearchResponse>(
    { url: `/search/trending`, method: "GET", params },
    options,
  );
};
/**
 * @summary 创建标签
 */
export const postTags = (
  apiCreateTagRequest: ApiCreateTagRequest,
  options?: SecondParameter<typeof customInstance<RenderResponseApiTagResponse>>,
) => {
  return customInstance<RenderResponseApiTagResponse>(
    {
      url: `/tags`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateTagRequest,
    },
    options,
  );
};
/**
 * @summary 获取标签详情
 */
export const getTagsTagId = (
  tagId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiTagResponse>>,
) => {
  return customInstance<RenderResponseApiTagResponse>(
    { url: `/tags/${tagId}`, method: "GET" },
    options,
  );
};
/**
 * @summary 获取标签帖子
 */
export const getTagsTagIdPosts = (
  tagId: string,
  params?: GetTagsTagIdPostsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiListPostsItemResponse>>,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/tags/${tagId}/posts`, method: "GET", params },
    options,
  );
};
/**
 * @summary 获取专题列表
 */
export const getTopics = (
  params?: GetTopicsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiTopicResponse>>,
) => {
  return customInstance<RenderResponseArrayApiTopicResponse>(
    { url: `/topics`, method: "GET", params },
    options,
  );
};
/**
 * @summary 获取专题详情
 */
export const getTopicsTopicId = (
  topicId: string,
  options?: SecondParameter<typeof customInstance<RenderResponseApiTopicResponse>>,
) => {
  return customInstance<RenderResponseApiTopicResponse>(
    { url: `/topics/${topicId}`, method: "GET" },
    options,
  );
};
/**
 * @summary 获取专题帖子
 */
export const getTopicsTopicIdPosts = (
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
  options?: SecondParameter<typeof customInstance<RenderResponseArrayApiListPostsItemResponse>>,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/topics/${topicId}/posts`, method: "GET", params },
    options,
  );
};
export type GetFeedRecommendedResult = NonNullable<Awaited<ReturnType<typeof getFeedRecommended>>>;
export type DeleteMeSearchHistoryResult = NonNullable<
  Awaited<ReturnType<typeof deleteMeSearchHistory>>
>;
export type GetMeSearchHistoryResult = NonNullable<Awaited<ReturnType<typeof getMeSearchHistory>>>;
export type GetSearchResult = NonNullable<Awaited<ReturnType<typeof getSearch>>>;
export type GetSearchSuggestionsResult = NonNullable<
  Awaited<ReturnType<typeof getSearchSuggestions>>
>;
export type GetSearchTrendingResult = NonNullable<Awaited<ReturnType<typeof getSearchTrending>>>;
export type PostTagsResult = NonNullable<Awaited<ReturnType<typeof postTags>>>;
export type GetTagsTagIdResult = NonNullable<Awaited<ReturnType<typeof getTagsTagId>>>;
export type GetTagsTagIdPostsResult = NonNullable<Awaited<ReturnType<typeof getTagsTagIdPosts>>>;
export type GetTopicsResult = NonNullable<Awaited<ReturnType<typeof getTopics>>>;
export type GetTopicsTopicIdResult = NonNullable<Awaited<ReturnType<typeof getTopicsTopicId>>>;
export type GetTopicsTopicIdPostsResult = NonNullable<
  Awaited<ReturnType<typeof getTopicsTopicIdPosts>>
>;
