/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * 小蓝书 API
 * 小蓝书后端接口文档
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../mutator";
import type {
  ApiCreateTagRequest,
  GetFeedRecommendedParams,
  GetSearchParams,
  GetSearchSuggestionsParams,
  GetSearchTrendingParams,
  GetTagsTagIdPostsParams,
  GetTopicsParams,
  GetTopicsTopicIdPostsParams,
  RenderErrorResponse,
  RenderResponseApiSearchResponse,
  RenderResponseApiTagResponse,
  RenderResponseApiTopicResponse,
  RenderResponseArrayApiListPostsItemResponse,
  RenderResponseArrayApiSearchHistoryResponse,
  RenderResponseArrayApiTopicResponse,
  RenderResponseArrayApiTrendingSearchResponse,
  RenderResponseWithoutData,
} from "../api.schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 获取发现流
 */
export const getFeedRecommended = (
  params?: GetFeedRecommendedParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/feed/recommended`, method: "GET", params, signal },
    options,
  );
};

export const getGetFeedRecommendedQueryKey = (params?: GetFeedRecommendedParams) => {
  return [`/feed/recommended`, ...(params ? [params] : [])] as const;
};

export const getGetFeedRecommendedQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeedRecommended>>,
  TError = RenderErrorResponse,
>(
  params?: GetFeedRecommendedParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedRecommended>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeedRecommendedQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedRecommended>>> = ({ signal }) =>
    getFeedRecommended(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeedRecommended>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFeedRecommendedQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeedRecommended>>
>;
export type GetFeedRecommendedQueryError = RenderErrorResponse;

export function useGetFeedRecommended<
  TData = Awaited<ReturnType<typeof getFeedRecommended>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetFeedRecommendedParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedRecommended>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedRecommended>>,
          TError,
          Awaited<ReturnType<typeof getFeedRecommended>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFeedRecommended<
  TData = Awaited<ReturnType<typeof getFeedRecommended>>,
  TError = RenderErrorResponse,
>(
  params?: GetFeedRecommendedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFeedRecommended>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedRecommended>>,
          TError,
          Awaited<ReturnType<typeof getFeedRecommended>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetFeedRecommended<
  TData = Awaited<ReturnType<typeof getFeedRecommended>>,
  TError = RenderErrorResponse,
>(
  params?: GetFeedRecommendedParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedRecommended>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取发现流
 */

export function useGetFeedRecommended<
  TData = Awaited<ReturnType<typeof getFeedRecommended>>,
  TError = RenderErrorResponse,
>(
  params?: GetFeedRecommendedParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedRecommended>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetFeedRecommendedQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 清空搜索历史
 */
export const deleteMeSearchHistory = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseWithoutData>(
    { url: `/me/search-history`, method: "DELETE", signal },
    options,
  );
};

export const getDeleteMeSearchHistoryMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMeSearchHistory>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMeSearchHistory>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["deleteMeSearchHistory"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMeSearchHistory>>,
    void
  > = () => {
    return deleteMeSearchHistory(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMeSearchHistoryMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMeSearchHistory>>
>;

export type DeleteMeSearchHistoryMutationError = RenderErrorResponse;

/**
 * @summary 清空搜索历史
 */
export const useDeleteMeSearchHistory = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteMeSearchHistory>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteMeSearchHistory>>, TError, void, TContext> => {
  return useMutation(getDeleteMeSearchHistoryMutationOptions(options), queryClient);
};
/**
 * @summary 获取搜索历史
 */
export const getMeSearchHistory = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiSearchHistoryResponse>(
    { url: `/me/search-history`, method: "GET", signal },
    options,
  );
};

export const getGetMeSearchHistoryQueryKey = () => {
  return [`/me/search-history`] as const;
};

export const getGetMeSearchHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeSearchHistory>>,
  TError = RenderErrorResponse,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeSearchHistory>>, TError, TData>>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeSearchHistoryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeSearchHistory>>> = ({ signal }) =>
    getMeSearchHistory(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMeSearchHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeSearchHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMeSearchHistory>>
>;
export type GetMeSearchHistoryQueryError = RenderErrorResponse;

export function useGetMeSearchHistory<
  TData = Awaited<ReturnType<typeof getMeSearchHistory>>,
  TError = RenderErrorResponse,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeSearchHistory>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeSearchHistory>>,
          TError,
          Awaited<ReturnType<typeof getMeSearchHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeSearchHistory<
  TData = Awaited<ReturnType<typeof getMeSearchHistory>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMeSearchHistory>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeSearchHistory>>,
          TError,
          Awaited<ReturnType<typeof getMeSearchHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMeSearchHistory<
  TData = Awaited<ReturnType<typeof getMeSearchHistory>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeSearchHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取搜索历史
 */

export function useGetMeSearchHistory<
  TData = Awaited<ReturnType<typeof getMeSearchHistory>>,
  TError = RenderErrorResponse,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeSearchHistory>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMeSearchHistoryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 综合搜索
 */
export const getSearch = (
  params: GetSearchParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiSearchResponse>(
    { url: `/search`, method: "GET", params, signal },
    options,
  );
};

export const getGetSearchQueryKey = (params?: GetSearchParams) => {
  return [`/search`, ...(params ? [params] : [])] as const;
};

export const getGetSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof getSearch>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearch>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSearch>>> = ({ signal }) =>
    getSearch(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSearch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getSearch>>>;
export type GetSearchQueryError = RenderErrorResponse;

export function useGetSearch<
  TData = Awaited<ReturnType<typeof getSearch>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearch>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSearch>>,
          TError,
          Awaited<ReturnType<typeof getSearch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSearch<
  TData = Awaited<ReturnType<typeof getSearch>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearch>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSearch>>,
          TError,
          Awaited<ReturnType<typeof getSearch>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSearch<
  TData = Awaited<ReturnType<typeof getSearch>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearch>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 综合搜索
 */

export function useGetSearch<
  TData = Awaited<ReturnType<typeof getSearch>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearch>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 搜索联想
 */
export const getSearchSuggestions = (
  params: GetSearchSuggestionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiSearchResponse>(
    { url: `/search/suggestions`, method: "GET", params, signal },
    options,
  );
};

export const getGetSearchSuggestionsQueryKey = (params?: GetSearchSuggestionsParams) => {
  return [`/search/suggestions`, ...(params ? [params] : [])] as const;
};

export const getGetSearchSuggestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSearchSuggestions>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchSuggestionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSearchSuggestions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSearchSuggestionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSearchSuggestions>>> = ({ signal }) =>
    getSearchSuggestions(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSearchSuggestions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSearchSuggestionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSearchSuggestions>>
>;
export type GetSearchSuggestionsQueryError = RenderErrorResponse;

export function useGetSearchSuggestions<
  TData = Awaited<ReturnType<typeof getSearchSuggestions>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchSuggestionsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSearchSuggestions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSearchSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getSearchSuggestions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSearchSuggestions<
  TData = Awaited<ReturnType<typeof getSearchSuggestions>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchSuggestionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSearchSuggestions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSearchSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getSearchSuggestions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSearchSuggestions<
  TData = Awaited<ReturnType<typeof getSearchSuggestions>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchSuggestionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSearchSuggestions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 搜索联想
 */

export function useGetSearchSuggestions<
  TData = Awaited<ReturnType<typeof getSearchSuggestions>>,
  TError = RenderErrorResponse,
>(
  params: GetSearchSuggestionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSearchSuggestions>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSearchSuggestionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取热搜词
 */
export const getSearchTrending = (
  params?: GetSearchTrendingParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiTrendingSearchResponse>(
    { url: `/search/trending`, method: "GET", params, signal },
    options,
  );
};

export const getGetSearchTrendingQueryKey = (params?: GetSearchTrendingParams) => {
  return [`/search/trending`, ...(params ? [params] : [])] as const;
};

export const getGetSearchTrendingQueryOptions = <
  TData = Awaited<ReturnType<typeof getSearchTrending>>,
  TError = RenderErrorResponse,
>(
  params?: GetSearchTrendingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearchTrending>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSearchTrendingQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSearchTrending>>> = ({ signal }) =>
    getSearchTrending(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSearchTrending>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSearchTrendingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSearchTrending>>
>;
export type GetSearchTrendingQueryError = RenderErrorResponse;

export function useGetSearchTrending<
  TData = Awaited<ReturnType<typeof getSearchTrending>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetSearchTrendingParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearchTrending>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSearchTrending>>,
          TError,
          Awaited<ReturnType<typeof getSearchTrending>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSearchTrending<
  TData = Awaited<ReturnType<typeof getSearchTrending>>,
  TError = RenderErrorResponse,
>(
  params?: GetSearchTrendingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearchTrending>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSearchTrending>>,
          TError,
          Awaited<ReturnType<typeof getSearchTrending>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSearchTrending<
  TData = Awaited<ReturnType<typeof getSearchTrending>>,
  TError = RenderErrorResponse,
>(
  params?: GetSearchTrendingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearchTrending>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取热搜词
 */

export function useGetSearchTrending<
  TData = Awaited<ReturnType<typeof getSearchTrending>>,
  TError = RenderErrorResponse,
>(
  params?: GetSearchTrendingParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSearchTrending>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSearchTrendingQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 创建标签
 */
export const postTags = (
  apiCreateTagRequest: ApiCreateTagRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiTagResponse>(
    {
      url: `/tags`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: apiCreateTagRequest,
      signal,
    },
    options,
  );
};

export const getPostTagsMutationOptions = <
  TError = RenderErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTags>>,
    TError,
    { data: ApiCreateTagRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTags>>,
  TError,
  { data: ApiCreateTagRequest },
  TContext
> => {
  const mutationKey = ["postTags"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTags>>,
    { data: ApiCreateTagRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postTags(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTagsMutationResult = NonNullable<Awaited<ReturnType<typeof postTags>>>;
export type PostTagsMutationBody = ApiCreateTagRequest;
export type PostTagsMutationError = RenderErrorResponse;

/**
 * @summary 创建标签
 */
export const usePostTags = <TError = RenderErrorResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTags>>,
      TError,
      { data: ApiCreateTagRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTags>>,
  TError,
  { data: ApiCreateTagRequest },
  TContext
> => {
  return useMutation(getPostTagsMutationOptions(options), queryClient);
};
/**
 * @summary 获取标签详情
 */
export const getTagsTagId = (
  tagId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiTagResponse>(
    { url: `/tags/${tagId}`, method: "GET", signal },
    options,
  );
};

export const getGetTagsTagIdQueryKey = (tagId: string) => {
  return [`/tags/${tagId}`] as const;
};

export const getGetTagsTagIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTagsTagId>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTagsTagIdQueryKey(tagId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTagsTagId>>> = ({ signal }) =>
    getTagsTagId(tagId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: tagId !== null && tagId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTagsTagId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTagsTagIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTagsTagId>>>;
export type GetTagsTagIdQueryError = RenderErrorResponse;

export function useGetTagsTagId<
  TData = Awaited<ReturnType<typeof getTagsTagId>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTagsTagId>>,
          TError,
          Awaited<ReturnType<typeof getTagsTagId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTagsTagId<
  TData = Awaited<ReturnType<typeof getTagsTagId>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTagsTagId>>,
          TError,
          Awaited<ReturnType<typeof getTagsTagId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTagsTagId<
  TData = Awaited<ReturnType<typeof getTagsTagId>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取标签详情
 */

export function useGetTagsTagId<
  TData = Awaited<ReturnType<typeof getTagsTagId>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTagsTagIdQueryOptions(tagId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取标签帖子
 */
export const getTagsTagIdPosts = (
  tagId: string,
  params?: GetTagsTagIdPostsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/tags/${tagId}/posts`, method: "GET", params, signal },
    options,
  );
};

export const getGetTagsTagIdPostsQueryKey = (tagId: string, params?: GetTagsTagIdPostsParams) => {
  return [`/tags/${tagId}/posts`, ...(params ? [params] : [])] as const;
};

export const getGetTagsTagIdPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTagsTagIdPosts>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  params?: GetTagsTagIdPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagIdPosts>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTagsTagIdPostsQueryKey(tagId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTagsTagIdPosts>>> = ({ signal }) =>
    getTagsTagIdPosts(tagId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: tagId !== null && tagId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTagsTagIdPosts>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTagsTagIdPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTagsTagIdPosts>>
>;
export type GetTagsTagIdPostsQueryError = RenderErrorResponse;

export function useGetTagsTagIdPosts<
  TData = Awaited<ReturnType<typeof getTagsTagIdPosts>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  params: undefined | GetTagsTagIdPostsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagIdPosts>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTagsTagIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getTagsTagIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTagsTagIdPosts<
  TData = Awaited<ReturnType<typeof getTagsTagIdPosts>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  params?: GetTagsTagIdPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagIdPosts>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTagsTagIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getTagsTagIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTagsTagIdPosts<
  TData = Awaited<ReturnType<typeof getTagsTagIdPosts>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  params?: GetTagsTagIdPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagIdPosts>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取标签帖子
 */

export function useGetTagsTagIdPosts<
  TData = Awaited<ReturnType<typeof getTagsTagIdPosts>>,
  TError = RenderErrorResponse,
>(
  tagId: string,
  params?: GetTagsTagIdPostsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTagsTagIdPosts>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTagsTagIdPostsQueryOptions(tagId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取专题列表
 */
export const getTopics = (
  params?: GetTopicsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiTopicResponse>(
    { url: `/topics`, method: "GET", params, signal },
    options,
  );
};

export const getGetTopicsQueryKey = (params?: GetTopicsParams) => {
  return [`/topics`, ...(params ? [params] : [])] as const;
};

export const getGetTopicsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTopics>>,
  TError = RenderErrorResponse,
>(
  params?: GetTopicsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTopicsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopics>>> = ({ signal }) =>
    getTopics(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTopics>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTopicsQueryResult = NonNullable<Awaited<ReturnType<typeof getTopics>>>;
export type GetTopicsQueryError = RenderErrorResponse;

export function useGetTopics<
  TData = Awaited<ReturnType<typeof getTopics>>,
  TError = RenderErrorResponse,
>(
  params: undefined | GetTopicsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopics>>,
          TError,
          Awaited<ReturnType<typeof getTopics>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTopics<
  TData = Awaited<ReturnType<typeof getTopics>>,
  TError = RenderErrorResponse,
>(
  params?: GetTopicsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopics>>,
          TError,
          Awaited<ReturnType<typeof getTopics>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTopics<
  TData = Awaited<ReturnType<typeof getTopics>>,
  TError = RenderErrorResponse,
>(
  params?: GetTopicsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取专题列表
 */

export function useGetTopics<
  TData = Awaited<ReturnType<typeof getTopics>>,
  TError = RenderErrorResponse,
>(
  params?: GetTopicsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopics>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTopicsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取专题详情
 */
export const getTopicsTopicId = (
  topicId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseApiTopicResponse>(
    { url: `/topics/${topicId}`, method: "GET", signal },
    options,
  );
};

export const getGetTopicsTopicIdQueryKey = (topicId: string) => {
  return [`/topics/${topicId}`] as const;
};

export const getGetTopicsTopicIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTopicsTopicId>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTopicsTopicIdQueryKey(topicId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopicsTopicId>>> = ({ signal }) =>
    getTopicsTopicId(topicId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: topicId !== null && topicId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTopicsTopicIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTopicsTopicId>>>;
export type GetTopicsTopicIdQueryError = RenderErrorResponse;

export function useGetTopicsTopicId<
  TData = Awaited<ReturnType<typeof getTopicsTopicId>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicsTopicId>>,
          TError,
          Awaited<ReturnType<typeof getTopicsTopicId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTopicsTopicId<
  TData = Awaited<ReturnType<typeof getTopicsTopicId>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicsTopicId>>,
          TError,
          Awaited<ReturnType<typeof getTopicsTopicId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTopicsTopicId<
  TData = Awaited<ReturnType<typeof getTopicsTopicId>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取专题详情
 */

export function useGetTopicsTopicId<
  TData = Awaited<ReturnType<typeof getTopicsTopicId>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicId>>, TError, TData>>;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTopicsTopicIdQueryOptions(topicId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 获取专题帖子
 */
export const getTopicsTopicIdPosts = (
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<RenderResponseArrayApiListPostsItemResponse>(
    { url: `/topics/${topicId}/posts`, method: "GET", params, signal },
    options,
  );
};

export const getGetTopicsTopicIdPostsQueryKey = (
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
) => {
  return [`/topics/${topicId}/posts`, ...(params ? [params] : [])] as const;
};

export const getGetTopicsTopicIdPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTopicsTopicIdPostsQueryKey(topicId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>> = ({ signal }) =>
    getTopicsTopicIdPosts(topicId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: topicId !== null && topicId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTopicsTopicIdPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTopicsTopicIdPosts>>
>;
export type GetTopicsTopicIdPostsQueryError = RenderErrorResponse;

export function useGetTopicsTopicIdPosts<
  TData = Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  params: undefined | GetTopicsTopicIdPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getTopicsTopicIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTopicsTopicIdPosts<
  TData = Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getTopicsTopicIdPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTopicsTopicIdPosts<
  TData = Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 获取专题帖子
 */

export function useGetTopicsTopicIdPosts<
  TData = Awaited<ReturnType<typeof getTopicsTopicIdPosts>>,
  TError = RenderErrorResponse,
>(
  topicId: string,
  params?: GetTopicsTopicIdPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTopicsTopicIdPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTopicsTopicIdPostsQueryOptions(topicId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
